-- AlterEnum
ALTER TYPE "RequestStatus" ADD VALUE 'ACKNOWLEDGED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_CEO_APPROVAL_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'CEO_APPROVED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'CEO_REJECTED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_CTO_APPROVAL_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'CTO_APPROVED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'CTO_REJECTED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_INVOICE_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_CFO_APPROVAL_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'CFO_APPROVED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'CFO_REJECTED_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PAYMENT_PROCESSING_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PAYMENT_DONE_IT';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_DELIVERY_IT';
