/**
 * Tenant Model Generator — P02 Task 6
 *
 * Reads the Prisma schema and generates a TypeScript module that exports
 * the exhaustive set of models containing a `tenantId` field. This ensures
 * the Prisma extension's `TENANT_SCOPED_MODELS` set is always complete.
 *
 * Usage: npx ts-node scripts/generate-tenant-models.ts
 *
 * Output: backend/src/generated/tenant-models.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const SCHEMA_PATH = join(__dirname, '..', 'prisma', 'schema.prisma');
const OUTPUT_PATH = join(__dirname, '..', 'src', 'generated', 'tenant-models.ts');

interface ModelInfo {
  name: string;
  hasTenantId: boolean;
  isEnum: boolean;
}

function parseSchemaModels(schema: string): ModelInfo[] {
  const models: ModelInfo[] = [];
  const modelRegex = /model\s+(\w+)\s*\{([^}]*)\}/gs;
  const enumRegex = /enum\s+(\w+)\s*\{([^}]*)\}/gs;

  // Track enums
  const enumNames = new Set<string>();
  let enumMatch: RegExpExecArray | null;
  while ((enumMatch = enumRegex.exec(schema)) !== null) {
    enumNames.add(enumMatch[1]);
  }

  let modelMatch: RegExpExecArray | null;
  while ((modelMatch = modelRegex.exec(schema)) !== null) {
    const name = modelMatch[1];
    const body = modelMatch[2];
    const hasTenantId = /^\s+tenantId\s/m.test(body);
    models.push({ name, hasTenantId, isEnum: false });
  }

  return models;
}

function generate(models: ModelInfo[]): string {
  const tenantModels = models.filter(m => m.hasTenantId);
  const allModels = models.map(m => m.name);

  const lines: string[] = [
    '/**',
    ' * AUTO-GENERATED — DO NOT EDIT',
    ' * Generated by scripts/generate-tenant-models.ts',
    ` * at ${new Date().toISOString()}`,
    ' *',
    ' * Lists all Prisma models that contain a tenantId column.',
    ' * The Prisma extension uses this to enforce tenant isolation.',
    ' */',
    '',
    `export const TENANT_SCOPED_MODELS: readonly string[] = [`,
  ];

  for (const m of tenantModels) {
    lines.push(`  '${m.name.charAt(0).toLowerCase() + m.name.slice(1)}',`);
  }

  lines.push('];');
  lines.push('');
  lines.push('export const ALL_PRISMA_MODELS: readonly string[] = [');
  for (const m of allModels) {
    lines.push(`  '${m.charAt(0).toLowerCase() + m.slice(1)}',`);
  }
  lines.push('];');
  lines.push('');
  lines.push(`// Tenant-scoped model count: ${tenantModels.length}`);
  lines.push(`// Total model count: ${allModels.length}`);
  lines.push('// Completeness: this file should be regenerated after any schema migration.');
  lines.push('');

  return lines.join('\n');
}

function main() {
  console.log('Reading Prisma schema from:', SCHEMA_PATH);
  const schema = readFileSync(SCHEMA_PATH, 'utf-8');
  const models = parseSchemaModels(schema);
  const output = generate(models);

  mkdirSync(join(__dirname, '..', 'src', 'generated'), { recursive: true });
  writeFileSync(OUTPUT_PATH, output, 'utf-8');

  const tenantModels = models.filter(m => m.hasTenantId);
  console.log(`\nGenerated ${OUTPUT_PATH}`);
  console.log(`Found ${tenantModels.length} tenant-scoped models out of ${models.length} total models:`);
  for (const m of tenantModels) {
    console.log(`  - ${m.name}`);
  }
}

main();