-- AlterEnum
ALTER TYPE "RequestStatus" ADD VALUE 'ACKNOWLEDGED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_CEO_APPROVAL_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'CEO_APPROVED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'CEO_REJECTED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_CFO_APPROVAL_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'CFO_APPROVED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'CFO_REJECTED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_GROUP_CEO_APPROVAL_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'GROUP_CEO_APPROVED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'GROUP_CEO_REJECTED_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'PAYMENT_PROCESSING_FIN';
ALTER TYPE "RequestStatus" ADD VALUE 'PAYMENT_COMPLETED_FIN';