import { useMemo, useState } from 'react';
import { EscalationRuleWithDetails } from '../../../services/serviceDesk.service';
import { roleDisplayName } from './RoleChipPicker';
export function EscalationOverviewTable({ rules, loading, onSelectRule }: { rules: EscalationRuleWithDetails[]; loading: boolean; onSelectRule: (rule: EscalationRuleWithDetails) => void }) {
    const [desk, setDesk] = useState('');
    const desks = useMemo(() => Array.from(new Map(rules.map(rule => [rule.requestType.serviceCategory.serviceDesk.id, rule.requestType.serviceCategory.serviceDesk])).values()), [rules]);
    const filtered = rules.filter(rule => !desk || rule.requestType.serviceCategory.serviceDesk.id === desk);
    if (loading) return <div className="space-y-3 rounded-xl border border-gray-200 p-4">{[1, 2, 3].map(row => <div key={row} className="h-10 animate-pulse rounded bg-gray-100" />)}</div>;
    return <section aria-label="Escalation overview" className="space-y-3"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-black text-[#101418]">Configured escalation rules</h3><select aria-label="Filter by service desk" value={desk} onChange={e => setDesk(e.target.value)} className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm"><option value="">All service desks</option>{desks.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>{filtered.length === 0 ? <div className="rounded-xl border border-dashed border-gray-200 py-10 text-center"><span className="material-symbols-outlined text-4xl text-[#8993a4]">timer</span><h4 className="mt-2 font-black text-[#101418]">No escalation rules configured yet</h4><p className="mt-1 text-sm text-[#8993a4]">Select a request type below to add your first rule.</p></div> : <div className="overflow-x-auto rounded-xl border border-gray-200"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-gray-200 bg-gray-50 text-xs font-black uppercase tracking-wide text-[#44546f]"><tr><th className="px-4 py-3">Service desk</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Request type</th><th className="px-4 py-3">SLA</th><th className="px-4 py-3">Trigger</th><th className="px-4 py-3">Notify roles</th><th className="px-4 py-3">Status</th></tr></thead><tbody className="divide-y divide-gray-100">{filtered.map(rule => <tr key={rule.id} onClick={() => onSelectRule(rule)} tabIndex={0} onKeyDown={e => { if (e.key === 'Enter') onSelectRule(rule); }} className="cursor-pointer hover:bg-blue-50/40"><td className="px-4 py-3 font-semibold">{rule.requestType.serviceCategory.serviceDesk.name}</td><td className="px-4 py-3">{rule.requestType.serviceCategory.name}</td><td className="px-4 py-3 font-bold">{rule.requestType.name}</td><td className="px-4 py-3">{rule.requestType.slaHours == null ? '—' : `${rule.requestType.slaHours}h`}</td><td className="px-4 py-3 font-black text-blue-700">+{rule.triggerHoursAfterBreach}h</td><td className="px-4 py-3">{rule.notifyRoles.map(roleDisplayName).join(', ')}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${rule.isActive ? 'bg-emerald-50 text-emerald-700' : 'bg-gray-100 text-gray-500'}`}>{rule.isActive ? 'Active' : 'Disabled'}</span></td></tr>)}</tbody></table></div>}</section>;
}
