import { FormEvent, useEffect, useState } from 'react';
import { EscalationRole, EscalationRule } from '../../../services/serviceDesk.service';
import { RoleChipPicker } from './RoleChipPicker';

type RuleInput = { triggerHoursAfterBreach: number; notifyRoles: string[]; label?: string };
export function EscalationRuleForm({ mode, initialValues, availableRoles, onSubmit, onCancel, saving, error }: { mode: 'add' | 'edit'; initialValues?: EscalationRule; availableRoles: EscalationRole[]; onSubmit: (data: RuleInput) => Promise<void>; onCancel: () => void; saving: boolean; error: string | null }) {
    const [hours, setHours] = useState(initialValues ? String(initialValues.triggerHoursAfterBreach) : '');
    const [label, setLabel] = useState(initialValues?.label || '');
    const [roles, setRoles] = useState(initialValues?.notifyRoles || []);
    useEffect(() => { setHours(initialValues ? String(initialValues.triggerHoursAfterBreach) : ''); setLabel(initialValues?.label || ''); setRoles(initialValues?.notifyRoles || []); }, [initialValues]);
    const value = hours === '' ? null : Number(hours);
    const submit = async (event: FormEvent) => { event.preventDefault(); if (value == null || !Number.isInteger(value) || value < 0 || value > 720 || roles.length === 0) return; await onSubmit({ triggerHoursAfterBreach: value, notifyRoles: roles, label: label || undefined }); };
    return <form onSubmit={submit} className="space-y-4 rounded-xl border border-gray-200 bg-white p-5"><div className="grid gap-4 md:grid-cols-2"><label className="block text-xs font-bold text-[#101418]">Trigger hours after breach<input type="number" min={0} max={720} step={1} required value={hours} onChange={e => setHours(e.target.value)} className="mt-1.5 w-full rounded-lg border border-gray-200 px-4 py-3 text-sm outline-none focus:border-[#0052cc]" />{value === 0 && <span className="mt-1 flex items-center gap-1 text-xs font-semibold text-amber-700"><span className="material-symbols-outlined text-sm">warning</span>Fires immediately on breach. Use with caution.</span>}{value != null && value > 168 && value <= 720 && <span className="mt-1 block text-xs font-semibold text-amber-700">Fires more than 7 days after breach.</span>}</label><label className="block text-xs font-bold text-[#101418]">Label (optional)<input type="text" value={label} onChange={e => setLabel(e.target.value)} placeholder="e.g. Manager escalation" className="mt-1.5 w-full rounded-lg border border-gray-200 px-4 py-3 text-sm outline-none focus:border-[#0052cc]" /></label></div><div><p className="mb-2 text-xs font-bold text-[#101418]">Notify roles</p><RoleChipPicker availableRoles={availableRoles} selectedRoles={roles} onChange={setRoles} disabled={saving} /></div>{error && <p className="rounded-lg bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</p>}<div className="flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-lg border border-gray-200 px-4 py-2 text-sm font-bold text-[#44546f]">Cancel</button><button type="submit" disabled={saving || value == null || roles.length === 0} className="flex items-center gap-2 rounded-lg bg-[#0052cc] px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving && <span className="animate-spin material-symbols-outlined text-lg">progress_activity</span>}{mode === 'add' ? 'Add rule' : 'Save changes'}</button></div></form>;
}
