import { useEffect, useState } from 'react';
import workflowService, { WorkflowStep, WorkflowType } from '../../../services/workflow.service';

export function SlaPauseConfig({ onMessage }: { onMessage: (message: string, error?: boolean) => void }) {
    const [workflowTypes, setWorkflowTypes] = useState<WorkflowType[]>([]);
    const [selectedWorkflowId, setSelectedWorkflowId] = useState('');
    const [workflowSteps, setWorkflowSteps] = useState<WorkflowStep[]>([]);
    const [saving, setSaving] = useState<string | null>(null);
    useEffect(() => { workflowService.getWorkflowTypes().then(setWorkflowTypes).catch(() => onMessage('Failed to load workflows.', true)); }, [onMessage]);
    useEffect(() => { if (!selectedWorkflowId) { setWorkflowSteps([]); return; } workflowService.getWorkflowType(selectedWorkflowId).then(workflow => setWorkflowSteps(workflow.steps || [])).catch(() => setWorkflowSteps([])); }, [selectedWorkflowId]);
    const toggle = async (step: WorkflowStep) => { setSaving(step.id); try { await workflowService.updateWorkflowStep(selectedWorkflowId, step.id, { slaPause: !step.slaPause }); setWorkflowSteps(current => current.map(item => item.id === step.id ? { ...item, slaPause: !item.slaPause } : item)); onMessage(`SLA pause ${step.slaPause ? 'disabled' : 'enabled'} for ${step.status}`); } catch { onMessage('Failed to update SLA pause setting.', true); } finally { setSaving(null); } };
    return <section className="border-t border-gray-200 pt-8"><div className="mb-4"><h2 className="text-lg font-black text-[#101418]">SLA Pause Configuration</h2><p className="mt-1 text-sm text-[#44546f]">Choose which workflow statuses pause the SLA timer.</p></div><div className="mb-5 rounded-xl border border-blue-100 bg-blue-50/70 p-4 text-sm text-blue-800"><span className="font-black">How these settings work: </span>SLA Pause and Escalation work together: paused statuses delay the SLA clock, which affects when escalation triggers fire.</div><label className="block max-w-md text-xs font-bold text-[#101418]">Workflow<select value={selectedWorkflowId} onChange={e => setSelectedWorkflowId(e.target.value)} className="mt-1.5 w-full rounded-lg border border-gray-200 bg-white px-4 py-3 text-sm"><option value="">Select workflow...</option>{workflowTypes.map(workflow => <option key={workflow.id} value={workflow.id}>{workflow.name} ({workflow.code})</option>)}</select></label>{selectedWorkflowId && workflowSteps.length > 0 && <div className="mt-5 overflow-x-auto rounded-xl border border-gray-200"><table className="min-w-[500px] w-full text-sm"><thead className="border-b border-gray-200 bg-gray-50"><tr><th className="sticky left-0 bg-gray-50 px-4 py-3 text-left font-semibold text-gray-700">Status</th><th className="px-4 py-3 text-left font-semibold text-gray-700">Label</th><th className="px-4 py-3 text-left font-semibold text-gray-700">Pause SLA</th><th className="px-4 py-3 text-left font-semibold text-gray-700">Type</th></tr></thead><tbody className="divide-y divide-gray-100">{[...workflowSteps].sort((a, b) => a.displayOrder - b.displayOrder).map(step => <tr key={step.id} className={`transition-colors ${step.slaPause ? 'bg-blue-50/30' : 'hover:bg-gray-50'}`}><td className="sticky left-0 bg-inherit px-4 py-3 font-mono text-xs text-indigo-700">{step.status}</td><td className="px-4 py-3 text-gray-900">{step.label}</td><td className="px-4 py-3"><button type="button" onClick={() => toggle(step)} disabled={saving === step.id} className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-bold ${step.slaPause ? 'bg-blue-100 text-blue-700' : 'bg-gray-100 text-gray-500'}`}>{saving === step.id ? <span className="animate-spin material-symbols-outlined text-sm">progress_activity</span> : <span className="material-symbols-outlined text-sm">{step.slaPause ? 'pause_circle' : 'play_circle'}</span>}{step.slaPause ? 'Paused' : 'Running'}</button></td><td className="px-4 py-3 text-xs text-gray-500">{step.isInitial ? 'Initial' : step.isFinal ? 'Final' : 'Step'}</td></tr>)}</tbody></table></div>}{selectedWorkflowId && workflowSteps.length === 0 && <div className="mt-5 rounded-xl bg-gray-50 py-6 text-center text-sm italic text-[#8993a4]">No steps configured for this workflow.</div>}</section>;
}
