-- Migration: Remove separate DCEO role and workflow, merge into GROUP_DCEO
-- Date: 2026-06-12

-- 1. Migrate existing requests from DCEO_FIN statuses to GROUP_DCEO statuses
UPDATE "requests" SET status = 'PENDING_GROUP_DCEO_APPROVAL' WHERE status = 'PENDING_DCEO_APPROVAL_FIN';
UPDATE "requests" SET status = 'GROUP_DCEO_APPROVED' WHERE status = 'DCEO_APPROVED_FIN';
UPDATE "requests" SET status = 'REJECTED' WHERE status = 'DCEO_REJECTED_FIN';

-- 2. Update users with DCEO executive role to GROUP_DCEO
UPDATE "users" SET executive_role = 'GROUP_DCEO' WHERE executive_role = 'DCEO';

-- 3. Update request_approvals with DCEO approver type to GROUP_DCEO
UPDATE "request_approvals" SET approver_type = 'GROUP_DCEO' WHERE approver_type = 'DCEO';

-- 4. Remove DCEO_FIN workflow transitions from WorkflowTransition table
DELETE FROM "workflow_transitions" WHERE from_status IN ('PENDING_DCEO_APPROVAL_FIN', 'DCEO_APPROVED_FIN', 'DCEO_REJECTED_FIN') OR to_status IN ('PENDING_DCEO_APPROVAL_FIN', 'DCEO_APPROVED_FIN', 'DCEO_REJECTED_FIN');

-- 5. Also remove CFO_APPROVED_FIN → PENDING_DCEO_APPROVAL_FIN transition
DELETE FROM "workflow_transitions" WHERE from_status = 'CFO_APPROVED_FIN' AND to_status = 'PENDING_DCEO_APPROVAL_FIN';

-- 6. Remove DCEO role from escalation rules notify_roles arrays
UPDATE "escalation_rules" SET notify_roles = array_replace(notify_roles, 'DCEO', 'GROUP_DCEO') WHERE 'DCEO' = ANY(notify_roles);

-- 7. Remove FINANCE_DCEO_DECISION notification event type if present (it will be superseded by FINANCE_GROUP_DCEO_DECISION)
DELETE FROM "notification_templates" WHERE event_type = 'FINANCE_DCEO_DECISION';

-- 8. Remove DCEO_FIN statuses from workflow steps
DELETE FROM "workflow_steps" WHERE status IN ('PENDING_DCEO_APPROVAL_FIN', 'DCEO_APPROVED_FIN', 'DCEO_REJECTED_FIN');

-- 9. Remove DCEO_FIN statuses from SLA pause config if any
-- (SLA pause is typically managed via the workflow_steps table which we already cleaned)

-- 10. PostgreSQL does not support ALTER TYPE ... REMOVE VALUE natively.
-- To remove enum values, we must re-create the enum types.
-- This is safe because we've already migrated all data references.

-- Re-create ExecutiveRole enum without DCEO
ALTER TABLE "users" ALTER COLUMN executive_role DROP DEFAULT;
ALTER TABLE "users" ALTER COLUMN executive_role TYPE VARCHAR(50) USING executive_role::text;
DROP TYPE IF EXISTS "ExecutiveRole";
CREATE TYPE "ExecutiveRole" AS ENUM ('CEO', 'CTO', 'CFO', 'COO', 'CHRO', 'CMO', 'GROUP_DCEO');
ALTER TABLE "users" ALTER COLUMN executive_role TYPE "ExecutiveRole" USING executive_role::"ExecutiveRole";

-- Re-create RequestStatus enum without DCEO_FIN values
-- First, convert all RequestStatus columns to text temporarily
ALTER TABLE "requests" ALTER COLUMN status DROP DEFAULT;
ALTER TABLE "requests" ALTER COLUMN status TYPE VARCHAR(100) USING status::text;
ALTER TABLE "workflow_steps" ALTER COLUMN status DROP DEFAULT;
ALTER TABLE "workflow_steps" ALTER COLUMN status TYPE VARCHAR(100) USING status::text;

DROP TYPE IF EXISTS "RequestStatus";
CREATE TYPE "RequestStatus" AS ENUM (
  'SUBMITTED', 'IN_REVIEW', 'ACTION_REQUIRED', 'APPROVED', 'REJECTED', 'RESOLVED', 'IN_PROGRESS', 'WAITING',
  'PENDING_CEO_APPROVAL', 'CEO_APPROVED', 'CEO_REJECTED', 'JOB_POSTED', 'PENDING_MANAGER_REVIEW',
  'MANAGER_APPROVED', 'INTERVIEW_SCHEDULED', 'INTERVIEW_FEEDBACK_PENDING', 'CANDIDATE_REJECTED_INTERVIEW',
  'HR_SCREENING', 'LOA_PENDING_APPROVAL', 'LOA_APPROVED', 'LOA_ISSUED', 'LOA_ACCEPTED', 'COMPLETED',
  'OFFBOARDING_SUBMITTED', 'OFFBOARDING_NOTICE_PERIOD', 'OFFBOARDING_KNOWLEDGE_TRANSFER',
  'OFFBOARDING_FINAL_WEEK', 'OFFBOARDING_EXIT_PROCEDURES', 'OFFBOARDING_COMPLETED',
  'ONBOARDING_SUBMITTED', 'ONBOARDING_PENDING_HR_APPROVAL', 'ONBOARDING_PRE_ARRIVAL_SETUP',
  'ONBOARDING_READY_FOR_DAY_1', 'ONBOARDING_DAY_1_ORIENTATION', 'ONBOARDING_WEEK_1_INTEGRATION',
  'ONBOARDING_MONTH_1_MILESTONE', 'ONBOARDING_MONTH_2_MILESTONE', 'ONBOARDING_MONTH_3_MILESTONE',
  'ONBOARDING_COMPLETED',
  'PENDING_MANAGER_APPROVAL_IT', 'MANAGER_APPROVED_IT', 'MANAGER_REJECTED_IT',
  'PENDING_VP_APPROVAL_IT', 'VP_APPROVED_IT', 'VP_REJECTED_IT',
  'PROCUREMENT_IN_PROGRESS', 'HARDWARE_ORDERED', 'HARDWARE_RECEIVED', 'SOFTWARE_PROVISIONED', 'ACKNOWLEDGED_IT',
  'PENDING_CEO_APPROVAL_IT', 'CEO_APPROVED_IT', 'CEO_REJECTED_IT',
  'PENDING_CTO_APPROVAL_IT', 'CTO_APPROVED_IT', 'CTO_REJECTED_IT',
  'PENDING_INVOICE_IT', 'PENDING_CFO_APPROVAL_IT', 'CFO_APPROVED_IT', 'CFO_REJECTED_IT',
  'PAYMENT_PROCESSING_IT', 'PAYMENT_DONE_IT', 'PENDING_DELIVERY_IT',
  'PENDING_MANAGER_APPROVAL_FIN', 'MANAGER_APPROVED_FIN', 'MANAGER_REJECTED_FIN',
  'PENDING_FINANCE_HEAD_APPROVAL', 'FINANCE_HEAD_APPROVED', 'FINANCE_HEAD_REJECTED',
  'PAYMENT_PROCESSING', 'PAYMENT_COMPLETED', 'REIMBURSEMENT_CLOSED',
  'FINANCE_PENDING_ACK', 'FINANCE_ACKNOWLEDGED', 'FINANCE_IN_PROGRESS',
  'PENDING_CFO_APPROVAL_FIN', 'CFO_APPROVED_FIN', 'CFO_REJECTED_FIN',
  'PENDING_GROUP_DCEO_APPROVAL', 'GROUP_DCEO_APPROVED', 'GROUP_DCEO_REJECTED',
  'PAYMENT_PROCESSING_FIN', 'AWAITING_PAYMENT_CONFIRMATION', 'PAYMENT_CONFIRMED_FIN', 'TICKET_CLOSED_FIN',
  'PENDING_FROM_ENTITY_APPROVAL', 'FROM_ENTITY_APPROVED', 'FROM_ENTITY_REJECTED',
  'PENDING_TO_ENTITY_APPROVAL', 'TO_ENTITY_APPROVED', 'TO_ENTITY_REJECTED',
  'CHARGEBACK_FINANCE_REVIEW', 'AWAITING_CHARGEBACK_CONFIRMATION', 'CHARGEBACK_COMPLETED',
  'CREDIT_APPLICATION_SUBMITTED', 'CREDIT_APPLICATION_IN_REVIEW', 'CREDIT_APPLICATION_APPROVED',
  'CREDIT_APPLICATION_REJECTED', 'CREDIT_APPLICATION_DISBURSED',
  'PENDING_CREDIT_ANALYSIS', 'CREDIT_ANALYSIS_IN_PROGRESS', 'CREDIT_ANALYSIS_COMPLETED',
  'PENDING_CREDIT_APPROVAL', 'CREDIT_APPROVED', 'CREDIT_REJECTED',
  'LOA_REJECTED',
  'VP_APPROVED', 'VP_REJECTED',
  'CHARGEBACK_PENDING', 'CHARGEBACK_APPROVED', 'CHARGEBACK_REJECTED',
  'ASSET_REQUEST_SUBMITTED', 'ASSET_REQUEST_APPROVED', 'ASSET_REQUEST_REJECTED', 'ASSET_REQUEST_FULFILLED',
  'ASSET_REQUEST_RETURNED',
  'PENDING_CREDIT_BUREAU_CHECK', 'CREDIT_BUREAU_CHECK_COMPLETED',
  'PENDING_CREDIT_SCORING', 'CREDIT_SCORING_COMPLETED',
  'PENDING_CREDIT_COMMITTEE_REVIEW', 'CREDIT_COMMITTEE_APPROVED', 'CREDIT_COMMITTEE_REJECTED',
  'PENDING_DISBURSEMENT', 'DISBURSED',
  'PENDING_PRICING_WORKSHEET', 'PRICING_WORKSHEET_COMPLETED',
  'SUSPENDED', 'CLOSED',
  'DELETED',
  'PENDING_ENTITY_APPROVAL', 'ENTITY_APPROVED', 'ENTITY_REJECTED'
);

ALTER TABLE "requests" ALTER COLUMN status TYPE "RequestStatus" USING status::"RequestStatus";
ALTER TABLE "workflow_steps" ALTER COLUMN status TYPE "RequestStatus" USING status::"RequestStatus";

-- 11. Also clean up UserRole enum if DCEO exists there
-- UserRole is a separate model/table, not an enum, so no changes needed.

-- 12. Ensure workflow transition from CFO_APPROVED_FIN → PENDING_GROUP_DCEO_APPROVAL exists
INSERT INTO "workflow_transitions" (from_status, to_status, transition_label, is_active, requires_comment)
SELECT 'CFO_APPROVED_FIN', 'PENDING_GROUP_DCEO_APPROVAL', 'ROUTE_TO_GROUP_DCEO', true, false
WHERE NOT EXISTS (
  SELECT 1 FROM "workflow_transitions" WHERE from_status = 'CFO_APPROVED_FIN' AND to_status = 'PENDING_GROUP_DCEO_APPROVAL'
);