-- Migration: Rename GROUP_CEO → GROUP_DCEO (data migration)
-- Date: 2026-06-05
-- Note: GROUP_DCEO role already exists in the DB. This migration migrates data and cleans up old values.

-- Step 1: Add new RequestStatus enum values (coexist with old ones temporarily)
ALTER TYPE "RequestStatus" ADD VALUE 'PENDING_GROUP_DCEO_APPROVAL';
ALTER TYPE "RequestStatus" ADD VALUE 'GROUP_DCEO_APPROVED';
ALTER TYPE "RequestStatus" ADD VALUE 'GROUP_DCEO_REJECTED';

-- Step 2: Migrate existing data

-- Requests
UPDATE requests SET status = 'PENDING_GROUP_DCEO_APPROVAL' WHERE status = 'PENDING_GROUP_CEO_APPROVAL';
UPDATE requests SET status = 'GROUP_DCEO_APPROVED' WHERE status = 'GROUP_CEO_APPROVED';
UPDATE requests SET status = 'GROUP_DCEO_REJECTED' WHERE status = 'GROUP_CEO_REJECTED';

-- Request approvals
UPDATE request_approvals SET approver_type = 'GROUP_DCEO' WHERE approver_type = 'GROUP_CEO';
-- Note: status column uses ApprovalStatus enum, not RequestStatus. Only approver_type needs updating.

-- Workflow steps
UPDATE workflow_steps SET status = 'PENDING_GROUP_DCEO_APPROVAL' WHERE status = 'PENDING_GROUP_CEO_APPROVAL';
UPDATE workflow_steps SET status = 'GROUP_DCEO_APPROVED' WHERE status = 'GROUP_CEO_APPROVED';
UPDATE workflow_steps SET status = 'GROUP_DCEO_REJECTED' WHERE status = 'GROUP_CEO_REJECTED';

-- Notification templates
UPDATE notification_templates SET event_type = 'FINANCE_GROUP_DCEO_DECISION' WHERE event_type = 'FINANCE_GROUP_CEO_DECISION';

-- Users (executive role)
UPDATE users SET executive_role = 'GROUP_DCEO' WHERE executive_role = 'GROUP_CEO';

-- Step 3: Move user_roles entries from GROUP_CEO role to GROUP_DCEO role
-- First, get GROUP_DCEO role id
-- Delete old GROUP_CEO role assignments and re-assign to GROUP_DCEO
INSERT INTO user_roles (user_id, role_id, assigned_at)
SELECT ur.user_id, 
       (SELECT id FROM roles WHERE name = 'GROUP_DCEO' LIMIT 1),
       ur.assigned_at
FROM user_roles ur 
JOIN roles r ON ur.role_id = r.id 
WHERE r.name = 'GROUP_CEO'
ON CONFLICT DO NOTHING;

-- Delete old GROUP_CEO role assignments
DELETE FROM user_roles WHERE role_id = (SELECT id FROM roles WHERE name = 'GROUP_CEO');

-- Delete the old GROUP_CEO role
DELETE FROM roles WHERE name = 'GROUP_CEO';

-- Step 4: Recreate ExecutiveRole enum to remove GROUP_CEO value
ALTER TYPE "ExecutiveRole" RENAME TO "ExecutiveRole_old";
CREATE TYPE "ExecutiveRole" AS ENUM ('CEO', 'CTO', 'CFO', 'COO', 'CHRO', 'CMO', 'GROUP_DCEO');
ALTER TABLE users ALTER COLUMN executive_role TYPE "ExecutiveRole" USING executive_role::"text"::"ExecutiveRole";
DROP TYPE "ExecutiveRole_old";

-- Step 5: Recreate RequestStatus enum to remove old GROUP_CEO_* values
ALTER TYPE "RequestStatus" RENAME TO "RequestStatus_old";
CREATE TYPE "RequestStatus" AS ENUM (
  'SUBMITTED', 'IN_REVIEW', 'ACTION_REQUIRED', 'APPROVED', 'REJECTED', 'RESOLVED',
  'IN_PROGRESS', 'WAITING', 'PENDING_CEO_APPROVAL', 'CEO_APPROVED', 'CEO_REJECTED',
  'JOB_POSTED', 'PENDING_MANAGER_REVIEW', 'MANAGER_APPROVED',
  'INTERVIEW_SCHEDULED', 'INTERVIEW_FEEDBACK_PENDING', 'CANDIDATE_REJECTED_INTERVIEW',
  'HR_SCREENING', 'LOA_PENDING_APPROVAL', 'LOA_APPROVED', 'LOA_ISSUED', 'LOA_ACCEPTED',
  'COMPLETED',
  'OFFBOARDING_SUBMITTED', 'OFFBOARDING_NOTICE_PERIOD', 'OFFBOARDING_KNOWLEDGE_TRANSFER',
  'OFFBOARDING_FINAL_WEEK', 'OFFBOARDING_EXIT_PROCEDURES', 'OFFBOARDING_COMPLETED',
  'ONBOARDING_SUBMITTED', 'ONBOARDING_PENDING_HR_APPROVAL', 'ONBOARDING_PRE_ARRIVAL_SETUP',
  'ONBOARDING_READY_FOR_DAY_1', 'ONBOARDING_DAY_1_ORIENTATION', 'ONBOARDING_WEEK_1_INTEGRATION',
  'ONBOARDING_MONTH_1_MILESTONE', 'ONBOARDING_MONTH_2_MILESTONE', 'ONBOARDING_MONTH_3_MILESTONE',
  'ONBOARDING_COMPLETED',
  'PENDING_MANAGER_APPROVAL_IT', 'MANAGER_APPROVED_IT', 'MANAGER_REJECTED_IT',
  'PENDING_VP_APPROVAL_IT', 'VP_APPROVED_IT', 'VP_REJECTED_IT',
  'PROCUREMENT_IN_PROGRESS', 'HARDWARE_ORDERED', 'HARDWARE_RECEIVED', 'SOFTWARE_PROVISIONED',
  'ACKNOWLEDGED_IT', 'PENDING_CEO_APPROVAL_IT', 'CEO_APPROVED_IT', 'CEO_REJECTED_IT',
  'PENDING_CTO_APPROVAL_IT', 'CTO_APPROVED_IT', 'CTO_REJECTED_IT',
  'PENDING_INVOICE_IT', 'PENDING_CFO_APPROVAL_IT', 'CFO_APPROVED_IT', 'CFO_REJECTED_IT',
  'PAYMENT_PROCESSING_IT', 'PAYMENT_DONE_IT', 'PENDING_DELIVERY_IT',
  'PENDING_MANAGER_APPROVAL_FIN', 'MANAGER_APPROVED_FIN', 'MANAGER_REJECTED_FIN',
  'PENDING_FINANCE_HEAD_APPROVAL', 'FINANCE_HEAD_APPROVED', 'FINANCE_HEAD_REJECTED',
  'PAYMENT_PROCESSING', 'PAYMENT_COMPLETED', 'REIMBURSEMENT_CLOSED',
  'FINANCE_PENDING_ACK', 'FINANCE_ACKNOWLEDGED', 'FINANCE_IN_PROGRESS',
  'PENDING_CFO_APPROVAL_FIN', 'CFO_APPROVED_FIN', 'CFO_REJECTED_FIN',
  'PENDING_GROUP_DCEO_APPROVAL', 'GROUP_DCEO_APPROVED', 'GROUP_DCEO_REJECTED',
  'PAYMENT_PROCESSING_FIN', 'AWAITING_PAYMENT_CONFIRMATION', 'PAYMENT_CONFIRMED_FIN', 'TICKET_CLOSED_FIN',
  'PENDING_FROM_ENTITY_APPROVAL', 'FROM_ENTITY_APPROVED', 'FROM_ENTITY_REJECTED',
  'PENDING_TO_ENTITY_APPROVAL', 'TO_ENTITY_APPROVED', 'TO_ENTITY_REJECTED',
  'CHARGEBACK_FINANCE_REVIEW', 'AWAITING_CHARGEBACK_CONFIRMATION', 'CHARGEBACK_COMPLETED',
  'PENDING_CEO_APPROVAL_FIN', 'CEO_APPROVED_FIN', 'CEO_REJECTED_FIN'
);
ALTER TABLE requests ALTER COLUMN status TYPE "RequestStatus" USING status::"text"::"RequestStatus";
ALTER TABLE workflow_steps ALTER COLUMN status TYPE "RequestStatus" USING status::"text"::"RequestStatus";
DROP TYPE "RequestStatus_old";