const VALID_TRANSITIONS: Record<string, string[]> = {
  SUBMITTED: ['IN_REVIEW', 'IN_PROGRESS', 'REJECTED'],
  IN_REVIEW: ['IN_PROGRESS', 'ACTION_REQUIRED', 'WAITING', 'REJECTED', 'RESOLVED'],
  IN_PROGRESS: ['ACTION_REQUIRED', 'WAITING', 'RESOLVED', 'REJECTED'],
  ACTION_REQUIRED: ['IN_PROGRESS', 'IN_REVIEW', 'RESOLVED', 'REJECTED'],
  WAITING: ['IN_PROGRESS', 'IN_REVIEW', 'RESOLVED'],
  APPROVED: ['RESOLVED'],
  RESOLVED: [],
  REJECTED: [],
  PENDING_CEO_APPROVAL: [],
  CEO_APPROVED: ['JOB_POSTED'],
  CEO_REJECTED: ['SUBMITTED'],
  JOB_POSTED: ['PENDING_MANAGER_REVIEW'],
  PENDING_MANAGER_REVIEW: [],
  MANAGER_APPROVED: ['INTERVIEW_SCHEDULED'],
  INTERVIEW_SCHEDULED: ['INTERVIEW_FEEDBACK_PENDING'],
  INTERVIEW_FEEDBACK_PENDING: ['HR_SCREENING', 'CANDIDATE_REJECTED_INTERVIEW'],
  CANDIDATE_REJECTED_INTERVIEW: ['JOB_POSTED'],
  HR_SCREENING: ['LOA_PENDING_APPROVAL'],
  LOA_PENDING_APPROVAL: [],
  LOA_APPROVED: ['LOA_ISSUED'],
  LOA_ISSUED: ['LOA_ACCEPTED'],
  LOA_ACCEPTED: ['COMPLETED'],
  COMPLETED: [],
  PENDING_MANAGER_APPROVAL_IT: [],
  MANAGER_APPROVED_IT: ['PROCUREMENT_IN_PROGRESS'],
  MANAGER_REJECTED_IT: [],
  PROCUREMENT_IN_PROGRESS: ['HARDWARE_ORDERED'],
  HARDWARE_ORDERED: ['HARDWARE_RECEIVED'],
  HARDWARE_RECEIVED: ['SOFTWARE_PROVISIONED'],
  SOFTWARE_PROVISIONED: ['RESOLVED'],
  PENDING_MANAGER_APPROVAL_FIN: [],
  MANAGER_APPROVED_FIN: ['PENDING_FINANCE_HEAD_APPROVAL'],
  MANAGER_REJECTED_FIN: [],
  PENDING_FINANCE_HEAD_APPROVAL: [],
  FINANCE_HEAD_APPROVED: ['PAYMENT_PROCESSING'],
  FINANCE_HEAD_REJECTED: [],
  PAYMENT_PROCESSING: ['PAYMENT_COMPLETED'],
  PAYMENT_COMPLETED: ['REIMBURSEMENT_CLOSED'],
  REIMBURSEMENT_CLOSED: [],
};

export function getValidNextStatuses(currentStatus: string): string[] {
  return VALID_TRANSITIONS[currentStatus] || [];
}

export function isValidTransition(from: string, to: string): boolean {
  const valid = VALID_TRANSITIONS[from];
  return valid ? valid.includes(to) : false;
}
