-- Set sla_pause = true on all approval-related workflow steps
-- These statuses represent "waiting for human approval" — SLA should pause
UPDATE "workflow_steps" SET "sla_pause" = true
WHERE status IN (
  'PENDING_MANAGER_APPROVAL_IT',
  'PENDING_VP_APPROVAL_IT',
  'PENDING_CEO_APPROVAL_IT',
  'PENDING_CTO_APPROVAL_IT',
  'PENDING_CFO_APPROVAL_IT',
  'PENDING_CEO_APPROVAL',
  'PENDING_MANAGER_REVIEW',
  'PENDING_MANAGER_APPROVAL_FIN',
  'PENDING_FINANCE_HEAD_APPROVAL',
  'PENDING_CFO_APPROVAL_FIN',
  'PENDING_GROUP_CEO_APPROVAL',
  'PENDING_FROM_ENTITY_APPROVAL',
  'PENDING_TO_ENTITY_APPROVAL',
  'LOA_PENDING_APPROVAL',
  'ONBOARDING_PENDING_HR_APPROVAL'
);