import { Request, Response, NextFunction } from 'express';
import jwt from 'jsonwebtoken';
import { AppError } from './error.middleware';
import { config } from '../config';
import { tokenService } from '../services/token.service';
import { permissionService } from '../services/permission.service';
import { runWithTenant } from '../lib/tenant-context';
import { runWithUser } from '../lib/user-context';

import prisma from '../utils/prisma';
import { logger } from '../utils/logger';

export interface AuthRequest extends Request {
    user?: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        roles: string[];
        permissions: string[];
        agentTeam?: string | null;
        tenantId?: string;
        entityId?: string | null; // P5-02: catalog entitlement filtering
        // P1-8 — MFA fields for requireMfa middleware
        mfaEnabled?: boolean;
        mustEnrollMfa?: boolean;
        mfaVerifiedAt?: Date | null;
    };
    jti?: string;
    tokenExp?: number;
}

export const authenticate = async (
    req: AuthRequest,
    _res: Response,
    next: NextFunction
) => {
    try {
        // Prefer cookie; fall back to Authorization header for API clients / tests
        let token: string | undefined;
        if (req.cookies?.access_token) {
            token = req.cookies.access_token;
        } else {
            const authHeader = req.headers.authorization;
            if (authHeader?.startsWith('Bearer ')) {
                token = authHeader.substring(7);
            }
        }

        if (!token) {
            throw new AppError('No token provided', 401);
        }

        const decoded = jwt.verify(token, config.jwt.secret) as {
            userId: string;
            email: string;
            tenantId?: string;
            jti?: string;
            exp?: number;
            iat?: number;
        };

        // Tokens must have a jti claim (all tokens generated by this system do)
        if (!decoded.jti) {
            throw new AppError('Token is missing required claims', 401);
        }

        // Check Redis blocklist — catches revoked tokens post-logout
        const revoked = await tokenService.isJtiRevoked(decoded.jti);
        if (revoked) {
            throw new AppError('Token has been revoked', 401);
        }

        // Check user-level revocation (password change / admin force-logout)
        const revokedAt = await tokenService.getUserRevocationTimestamp(decoded.userId);
        const tokenIssuedAt = decoded.iat ? decoded.iat * 1000 : 0;
        if (revokedAt > 0 && tokenIssuedAt < revokedAt) {
            throw new AppError('Token has been revoked', 401);
        }

        const user = await prisma.user.findUnique({
            where: { id: decoded.userId },
            include: { roles: { include: { role: true } } },
        });

        if (!user || !user.isActive) {
            throw new AppError('User not found or inactive', 401);
        }

        const roles = user.roles.map((ur) => ur.role.name);

        // Load permission names from cache or DB
        let permissions: string[] = [];
        try {
            permissions = await permissionService.getUserPermissions(user.id);
        } catch {
            // Non-critical — fall back to empty set (role-based auth still works)
        }

        req.user = {
            id: user.id,
            email: user.email,
            firstName: user.firstName,
            lastName: user.lastName,
            roles,
            permissions,
            agentTeam: user.agentTeam,
            tenantId: user.tenantId ?? undefined,
            entityId: user.entityId ?? undefined, // P5-02
            // P1-8 — MFA fields for requireMfa middleware
            mfaEnabled: user.mfaEnabled,
            mustEnrollMfa: user.mustEnrollMfa,
            mfaVerifiedAt: user.mfaVerifiedAt,
        };
        // Populate jti and tokenExp so logout can revoke the specific token
        req.jti = decoded.jti;
        req.tokenExp = decoded.exp;

        // Wrap the remainder of the request in tenant + user context so all
        // downstream Prisma queries are automatically scoped and auto-audit
        // can attribute writes to the real user.
        const tenantId = user.tenantId;
        const userCtx = {
          userId: user.id,
          email: user.email,
          ipAddress: req.ip,
          userAgent: req.get('user-agent') ?? undefined,
        };
        const wrapNext = async () => next();
        if (tenantId) {
          return runWithTenant(tenantId, async () => runWithUser(userCtx, wrapNext));
        }
        return runWithUser(userCtx, wrapNext);
    } catch (error) {
        if (error instanceof jwt.JsonWebTokenError) {
            next(new AppError('Invalid token', 401));
        } else if (error instanceof jwt.TokenExpiredError) {
            next(new AppError('Token expired', 401));
        } else {
            next(error);
        }
    }
};

export const optionalAuth = async (
    req: AuthRequest,
    _res: Response,
    next: NextFunction
) => {
    try {
        let token: string | undefined;
        if (req.cookies?.access_token) {
            token = req.cookies.access_token;
        } else {
            const authHeader = req.headers.authorization;
            if (authHeader?.startsWith('Bearer ')) {
                token = authHeader.substring(7);
            }
        }

        if (!token) return next();

        const decoded = jwt.verify(token, config.jwt.secret) as {
            userId: string;
            email: string;
            jti?: string;
        };

        if (decoded.jti) {
            const revoked = await tokenService.isJtiRevoked(decoded.jti);
            if (revoked) return next();

            // Check user-level revocation
            const revokedAt = await tokenService.getUserRevocationTimestamp(decoded.userId);
            const tokenIssuedAt = (decoded as any).iat ? (decoded as any).iat * 1000 : 0;
            if (revokedAt > 0 && tokenIssuedAt < revokedAt) return next();
        }

        const user = await prisma.user.findUnique({
            where: { id: decoded.userId },
            include: { roles: { include: { role: true } } },
        });

        if (user?.isActive) {
            const roles = user.roles.map((ur) => ur.role.name);

            let permissions: string[] = [];
            try {
                permissions = await permissionService.getUserPermissions(user.id);
            } catch {
                // Non-critical
            }

            req.user = {
                id: user.id,
                email: user.email,
                firstName: user.firstName,
                lastName: user.lastName,
                roles,
                permissions,
                agentTeam: user.agentTeam,
                tenantId: user.tenantId ?? undefined,
            };
        }

        // Set tenant context if user has a tenant
        if (user?.tenantId) {
            return runWithTenant(user.tenantId, async () => next());
        }
        next();
    } catch {
        next();
    }
};

// ── P0-5: Service API Key authentication ────────────────────────────────────────
// For service-to-service endpoints (e.g. AV scan callback) that should NOT
// be accessible via user JWT. Validates the X-Service-API-Key header against
// the SERVICE_API_KEY env var. Falls back to INTERNAL_SCAN_TOKEN for backward
// compatibility with the existing ClamAV scan-document pattern.

export const requireServiceApiKey = (
    req: Request,
    _res: Response,
    next: NextFunction
) => {
    const apiKey = req.header('x-service-api-key') || req.header('x-internal-scan-token');
    const configuredKey = config.security.serviceApiKey || config.security.internalScanToken;

    if (!configuredKey) {
        return next(new AppError('Service API key is not configured on the server', 503));
    }

    if (!apiKey || apiKey !== configuredKey) {
        return next(new AppError('Valid service API key is required', 403));
    }

    next();
};

export function hasRole(req: AuthRequest, ...roles: string[]): boolean {
    return roles.some((role) => req.user?.roles.includes(role) ?? false);
}

/**
 * SSE authentication middleware.
 *
 * P1-02: Cookie-based auth is now the primary method (withCredentials).
 * Query-param ?token= is retained as a fallback for non-browser clients but
 * is deprecated — it leaks JWTs into server logs and browser history.
 *
 * Priority order:
 *   1. HttpOnly cookie (access_token)  — browser SSE with withCredentials
 *   2. Authorization header            — curl/API clients
 *   3. Query param (?token=)           — deprecated fallback
 */
export const sseAuth = async (
    req: AuthRequest,
    res: Response,
    next: NextFunction
) => {
    try {
        let token: string | undefined;

        // 1. Cookie (preferred — browser SSE with withCredentials)
        if (req.cookies?.access_token) {
            token = req.cookies.access_token;
        }
        // 2. Authorization header (API clients / curl)
        else if (req.headers.authorization?.startsWith('Bearer ')) {
            token = req.headers.authorization.substring(7);
        }
        // 3. Query param (deprecated — leaks into logs/history)
        else if ((req.query as Record<string, unknown>).token) {
            token = String((req.query as Record<string, unknown>).token);
            logger.warn('SSE auth via query token is deprecated; use cookie or Authorization header instead');
        }

        if (!token) {
            res.status(401).json({ error: 'No token provided' });
            return;
        }

        const decoded = jwt.verify(token, config.jwt.secret) as {
            userId: string;
            email: string;
            tenantId?: string;
            jti?: string;
            exp?: number;
            iat?: number;
        };

        if (!decoded.jti) {
            res.status(401).json({ error: 'Token is missing required claims' });
            return;
        }

        const revoked = await tokenService.isJtiRevoked(decoded.jti);
        if (revoked) {
            res.status(401).json({ error: 'Token has been revoked' });
            return;
        }

        const revokedAt = await tokenService.getUserRevocationTimestamp(decoded.userId);
        const tokenIssuedAt = decoded.iat ? decoded.iat * 1000 : 0;
        if (revokedAt > 0 && tokenIssuedAt < revokedAt) {
            res.status(401).json({ error: 'Token has been revoked' });
            return;
        }

        const user = await prisma.user.findUnique({
            where: { id: decoded.userId },
            include: { roles: { include: { role: true } } },
        });

        if (!user || !user.isActive) {
            res.status(401).json({ error: 'User not found or inactive' });
            return;
        }

        const roles = user.roles.map((ur) => ur.role.name);

        let permissions: string[] = [];
        try {
            permissions = await permissionService.getUserPermissions(user.id);
        } catch {
            // Non-critical
        }

        req.user = {
            id: user.id,
            email: user.email,
            firstName: user.firstName,
            lastName: user.lastName,
            roles,
            permissions,
            agentTeam: user.agentTeam,
            tenantId: user.tenantId ?? undefined,
        };
        req.jti = decoded.jti;
        req.tokenExp = decoded.exp;

        // Set tenant context if user has a tenant
        if (user.tenantId) {
            return runWithTenant(user.tenantId, async () => next());
        }
        next();
    } catch (error) {
        if (error instanceof jwt.JsonWebTokenError) {
            res.status(401).json({ error: 'Invalid token' });
        } else if (error instanceof jwt.TokenExpiredError) {
            res.status(401).json({ error: 'Token expired' });
        } else {
            res.status(401).json({ error: 'Authentication failed' });
        }
    }
};

export const authorize = (...roles: string[]) => {
    return (req: AuthRequest, _res: Response, next: NextFunction) => {
        if (!req.user) {
            return next(new AppError('Not authenticated', 401));
        }
        const hasRole = roles.some((role) => req.user!.roles.includes(role));
        if (!hasRole) {
            return next(new AppError('Insufficient permissions', 403));
        }
        next();
    };
};

/**
 * Permission-based authorization middleware.
 *
 * Checks that the authenticated user has the specified permission name.
 * Permission names follow the format `resource:action` (e.g. `request:create`, `admin:access`).
 *
 * Usage:
 *   router.get('/data', authenticate, requirePermission('report:read'), controller.getData);
 *
 * The permission is checked against `req.user.permissions` which is loaded
 * during authentication from the RolePermission join table (with Redis caching).
 */
export const requirePermission = (...permissionNames: string[]) => {
    return (req: AuthRequest, _res: Response, next: NextFunction) => {
        if (!req.user) {
            return next(new AppError('Not authenticated', 401));
        }

        const hasPermission = permissionNames.some((name) =>
            req.user!.permissions.includes(name)
        );

        if (!hasPermission) {
            return next(new AppError(
                `Missing required permission: ${permissionNames.join(' or ')}`,
                403
            ));
        }

        next();
    };
};