/**
 * Compatibility contract for legacy code paths while request.status is now a
 * catalog-backed string. Runtime validation must use RequestStatusDefinition.
 */
export const LEGACY_REQUEST_STATUS_CODES = [
  'SUBMITTED', 'IN_REVIEW', 'ACTION_REQUIRED', 'APPROVED', 'REJECTED', 'CANCELLED', 'RESOLVED', 'IN_PROGRESS', 'WAITING',
  'PENDING_CEO_APPROVAL', 'CEO_APPROVED', 'CEO_REJECTED', 'JOB_POSTED', 'PENDING_MANAGER_REVIEW', 'MANAGER_APPROVED',
  'INTERVIEW_SCHEDULED', 'INTERVIEW_FEEDBACK_PENDING', 'CANDIDATE_REJECTED_INTERVIEW', 'HR_SCREENING', 'LOA_PENDING_APPROVAL',
  'LOA_APPROVED', 'LOA_ISSUED', 'LOA_ACCEPTED', 'LOA_REJECTED', 'COMPLETED', 'OFFBOARDING_SUBMITTED',
  'OFFBOARDING_NOTICE_PERIOD', 'OFFBOARDING_KNOWLEDGE_TRANSFER', 'OFFBOARDING_FINAL_WEEK', 'OFFBOARDING_EXIT_PROCEDURES',
  'OFFBOARDING_COMPLETED', 'ONBOARDING_SUBMITTED', 'ONBOARDING_PENDING_HR_APPROVAL', 'ONBOARDING_PRE_ARRIVAL_SETUP',
  'ONBOARDING_READY_FOR_DAY_1', 'ONBOARDING_DAY_1_ORIENTATION', 'ONBOARDING_WEEK_1_INTEGRATION', 'ONBOARDING_MONTH_1_MILESTONE',
  'ONBOARDING_MONTH_2_MILESTONE', 'ONBOARDING_MONTH_3_MILESTONE', 'ONBOARDING_COMPLETED', 'PENDING_MANAGER_APPROVAL_IT',
  'MANAGER_APPROVED_IT', 'MANAGER_REJECTED_IT', 'PENDING_VP_APPROVAL_IT', 'VP_APPROVED_IT', 'VP_REJECTED_IT',
  'PROCUREMENT_IN_PROGRESS', 'HARDWARE_ORDERED', 'HARDWARE_RECEIVED', 'SOFTWARE_PROVISIONED', 'ACKNOWLEDGED_IT',
  'PENDING_CEO_APPROVAL_IT', 'CEO_APPROVED_IT', 'CEO_REJECTED_IT', 'PENDING_CTO_APPROVAL_IT', 'CTO_APPROVED_IT',
  'CTO_REJECTED_IT', 'PENDING_INVOICE_IT', 'PENDING_CFO_APPROVAL_IT', 'CFO_APPROVED_IT', 'CFO_REJECTED_IT',
  'PAYMENT_PROCESSING_IT', 'PAYMENT_DONE_IT', 'PENDING_DELIVERY_IT', 'PENDING_MANAGER_APPROVAL_FIN', 'MANAGER_APPROVED_FIN',
  'MANAGER_REJECTED_FIN', 'PENDING_FINANCE_HEAD_APPROVAL', 'FINANCE_HEAD_APPROVED', 'FINANCE_HEAD_REJECTED',
  'PAYMENT_PROCESSING', 'PAYMENT_COMPLETED', 'REIMBURSEMENT_CLOSED', 'FINANCE_PENDING_ACK', 'FINANCE_ACKNOWLEDGED',
  'FINANCE_IN_PROGRESS', 'PENDING_CFO_APPROVAL_FIN', 'CFO_APPROVED_FIN', 'CFO_REJECTED_FIN', 'PENDING_GROUP_DCEO_APPROVAL',
  'GROUP_DCEO_APPROVED', 'GROUP_DCEO_REJECTED', 'PAYMENT_PROCESSING_FIN', 'AWAITING_PAYMENT_CONFIRMATION',
  'PAYMENT_CONFIRMED_FIN', 'TICKET_CLOSED_FIN', 'PENDING_FROM_ENTITY_APPROVAL', 'FROM_ENTITY_APPROVED',
  'FROM_ENTITY_REJECTED', 'PENDING_TO_ENTITY_APPROVAL', 'TO_ENTITY_APPROVED', 'TO_ENTITY_REJECTED', 'CHARGEBACK_FINANCE_REVIEW',
  'AWAITING_CHARGEBACK_CONFIRMATION', 'CHARGEBACK_COMPLETED', 'PENDING_CEO_APPROVAL_FIN', 'CEO_APPROVED_FIN', 'CEO_REJECTED_FIN',
] as const;

export type RequestStatus = string;
export const RequestStatus = Object.fromEntries(
  LEGACY_REQUEST_STATUS_CODES.map((code) => [code, code]),
) as Record<(typeof LEGACY_REQUEST_STATUS_CODES)[number], string>;
