/**
 * Operation Control Registry — the single source of truth for security
 * metadata on every API operation.
 *
 * Every route in backend/src/routes/ and backend/src/credit/routes/ MUST have
 * a corresponding entry here. The coverage test (operation-control.coverage.test.ts)
 * will fail the build if any operation is missing or duplicate.
 *
 * Batch 1 (P01): Critical user, file, notification, PDF, export endpoints.
 * Batch 2 (P02 T9): Request domain endpoints — secured with authorizeResource.
 *
 * @see backend/src/security/operation-control.types.ts
 */

import { OperationControl } from './operation-control.types';

export const operationControls: OperationControl[] = [
  // ── User endpoints (finding #6, #35) ──────────────────────────────
  {
    method: 'GET',
    path: '/users',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.list',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:read',
    validation: 'uuidParams',
    responseSchema: 'UserSummaryDto',
    rateTier: 'read',
    auditEvent: 'user.read',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:update',
    resourcePolicy: 'user:update',
    validation: 'updateUserSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.update',
    auditFindingIds: [6, 35],
  },
  {
    method: 'DELETE',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:delete',
    resourcePolicy: 'user:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.delete',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/users',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:create',
    validation: 'createUserSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.create',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/me',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:read-own',
    validation: 'none',
    responseSchema: 'UserProfileDto',
    rateTier: 'read',
    auditEvent: 'user.me',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/me',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:update-own',
    validation: 'updateProfileSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.updateMe',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/me/password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:change-password',
    validation: 'changePasswordSchema',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.changePassword',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/agents',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list-agents',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.listAgents',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/staff',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list-staff',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.listStaff',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/search',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:search',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.search',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/users/:id/roles',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:assign-roles',
    validation: 'assignRolesSchema',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.assignRoles',
    auditFindingIds: [6, 35],
  },

  // ── Auth endpoints (finding #6, #35) ──────────────────────────────
  {
    method: 'POST',
    path: '/auth/login',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:login',
    validation: 'loginSchema',
    responseSchema: 'AuthResponse',
    rateTier: 'auth',
    auditEvent: 'auth.login',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/logout',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:logout',
    validation: 'none',
    responseSchema: 'none',
    rateTier: 'auth',
    auditEvent: 'auth.logout',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/refresh',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:refresh',
    validation: 'none',
    responseSchema: 'AuthResponse',
    rateTier: 'auth',
    auditEvent: 'auth.refresh',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/forgot-password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:forgot-password',
    validation: 'forgotPasswordSchema',
    responseSchema: 'none',
    rateTier: 'auth',
    auditEvent: 'auth.forgotPassword',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/reset-password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:reset-password',
    validation: 'resetPasswordSchema',
    responseSchema: 'none',
    rateTier: 'auth',
    auditEvent: 'auth.resetPassword',
    auditFindingIds: [6, 35],
  },

  // ── File download (finding #7, #83, #84) ──────────────────────────
  {
    method: 'GET',
    path: '/files/download/*',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'file:download',
    resourcePolicy: 'attachment:download',
    validation: 'none',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'file.download',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'POST',
    path: '/files/upload',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'file:upload',
    resourcePolicy: 'attachment:upload',
    validation: 'multipartUpload',
    responseSchema: 'UploadResult',
    rateTier: 'write',
    auditEvent: 'file.upload',
    auditFindingIds: [7, 83, 84],
  },

  // ── Request endpoints (P02 T9 — secured with authorizeResource) ───
  {
    method: 'GET',
    path: '/requests',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:list',
    validation: 'none',
    responseSchema: 'RequestListDto',
    rateTier: 'read',
    auditEvent: 'request.list',
    auditFindingIds: [8, 10, 11, 12, 16, 55],
  },
  {
    method: 'POST',
    path: '/requests',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:create',
    resourcePolicy: 'request:create',
    validation: 'createRequestSchema',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.create',
    auditFindingIds: [8, 10, 12, 19],
  },
  {
    method: 'GET',
    path: '/requests/pending-approvals',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:list-pending',
    validation: 'none',
    responseSchema: 'RequestListDto',
    rateTier: 'read',
    auditEvent: 'request.pendingApprovals',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'POST',
    path: '/requests/bulk-action',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:bulk-action',
    validation: 'none',
    responseSchema: 'BulkActionResult',
    rateTier: 'write',
    auditEvent: 'request.bulkAction',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'GET',
    path: '/requests/recent-services',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:list-own',
    validation: 'none',
    responseSchema: 'ServiceTypeDto[]',
    rateTier: 'read',
    auditEvent: 'request.recentServices',
    auditFindingIds: [8, 10],
  },
  {
    method: 'POST',
    path: '/requests/export/xlsx',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'request:export',
    validation: 'exportFilterSchema',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.export.xlsx',
    auditFindingIds: [35],
  },
  {
    method: 'GET',
    path: '/requests/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'RequestDto',
    rateTier: 'read',
    auditEvent: 'request.read',
    auditFindingIds: [8, 10, 11, 16, 55],
  },
  {
    method: 'PUT',
    path: '/requests/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'updateRequestSchema',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.update',
    auditFindingIds: [8, 10, 12, 16],
  },
  {
    method: 'DELETE',
    path: '/requests/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:delete',
    resourcePolicy: 'request:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'request.delete',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'GET',
    path: '/requests/:id/export/pdf',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'request:export',
    validation: 'uuidParams',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.export.pdf',
    auditFindingIds: [35],
  },
  {
    method: 'GET',
    path: '/requests/:id/activities',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'ActivityDto[]',
    rateTier: 'read',
    auditEvent: 'request.activity.list',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/requests/:id/activities',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'addActivitySchema',
    responseSchema: 'ActivityDto',
    rateTier: 'write',
    auditEvent: 'request.activity.add',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/requests/:id/attachments',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'attachment:upload',
    validation: 'multipartUpload',
    responseSchema: 'AttachmentDto',
    rateTier: 'write',
    auditEvent: 'request.attachment.upload',
    auditFindingIds: [7, 13, 14],
  },
  {
    method: 'GET',
    path: '/requests/:id/attachments/:attachmentId',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'attachment:download',
    validation: 'uuidParams',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.attachment.download',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'DELETE',
    path: '/requests/:id/attachments/:attachmentId',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'attachment:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'request.attachment.delete',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'PUT',
    path: '/requests/:id/assign',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'uuidParams',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.assign',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'PUT',
    path: '/requests/:id/status',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'uuidParams',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.updateStatus',
    auditFindingIds: [8, 10, 12],
  },

  // ── Request participants (finding #13–#16) ─────────────────────────
  {
    method: 'GET',
    path: '/requests/:id/participants',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'ParticipantDto[]',
    rateTier: 'read',
    auditEvent: 'request.participant.list',
    auditFindingIds: [13, 14, 15, 16],
  },
  {
    method: 'POST',
    path: '/requests/:id/participants',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'addParticipantSchema',
    responseSchema: 'ParticipantDto',
    rateTier: 'write',
    auditEvent: 'request.participant.add',
    auditFindingIds: [15, 16],
  },
  {
    method: 'DELETE',
    path: '/requests/:id/participants/:userId',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'request.participant.remove',
    auditFindingIds: [15, 16],
  },

  // ── Notification mutations (finding #17, #18) ──────────────────────
  {
    method: 'GET',
    path: '/notifications',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:list',
    validation: 'none',
    responseSchema: 'NotificationDto[]',
    rateTier: 'read',
    auditEvent: 'notification.list',
    auditFindingIds: [17, 18],
  },
  {
    method: 'GET',
    path: '/notifications/unread-count',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:list',
    validation: 'none',
    responseSchema: 'UnreadCountDto',
    rateTier: 'read',
    auditEvent: 'notification.unreadCount',
    auditFindingIds: [17, 18],
  },
  {
    method: 'PUT',
    path: '/notifications/:id/read',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:update',
    validation: 'uuidParams',
    responseSchema: 'NotificationDto',
    rateTier: 'write',
    auditEvent: 'notification.markRead',
    auditFindingIds: [17, 18],
  },
  {
    method: 'PUT',
    path: '/notifications/read-all',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:update',
    validation: 'none',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'notification.markAllRead',
    auditFindingIds: [17, 18],
  },
  {
    method: 'DELETE',
    path: '/notifications/:id',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'notification.delete',
    auditFindingIds: [17, 18],
  },

  // ── PDF jobs (finding #83, #84) ────────────────────────────────────
  {
    method: 'GET',
    path: '/pdf-jobs/:jobId',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'pdfJob:read',
    validation: 'uuidParams',
    responseSchema: 'PdfJobDto',
    rateTier: 'read',
    auditEvent: 'pdfJob.read',
    auditFindingIds: [83, 84],
  },

  // ── Departments (P02 T7) ──────────────────────────────────────────
  {
    method: 'GET',
    path: '/departments',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'department:read',
    resourcePolicy: 'department:list',
    validation: 'none',
    responseSchema: 'DepartmentDto[]',
    rateTier: 'read',
    auditEvent: 'department.list',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'GET',
    path: '/departments/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'department:read',
    resourcePolicy: 'department:read',
    validation: 'uuidParams',
    responseSchema: 'DepartmentDto',
    rateTier: 'read',
    auditEvent: 'department.read',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'POST',
    path: '/departments',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:create',
    validation: 'createDepartmentSchema',
    responseSchema: 'DepartmentDto',
    rateTier: 'write',
    auditEvent: 'department.create',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'PUT',
    path: '/departments/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:update',
    validation: 'updateDepartmentSchema',
    responseSchema: 'DepartmentDto',
    rateTier: 'write',
    auditEvent: 'department.update',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'DELETE',
    path: '/departments/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'department.delete',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'POST',
    path: '/departments/:id/members',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:manage-members',
    validation: 'addMemberSchema',
    responseSchema: 'MembershipDto',
    rateTier: 'write',
    auditEvent: 'department.addMember',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'DELETE',
    path: '/departments/members/:membershipId',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:manage-members',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'department.removeMember',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'GET',
    path: '/departments/grants/:userId',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'department:read',
    resourcePolicy: 'department:read-grants',
    validation: 'uuidParams',
    responseSchema: 'PrincipalGrantDto[]',
    rateTier: 'read',
    auditEvent: 'department.grants',
    auditFindingIds: [1, 2, 29, 30],
  },

  // ── Announcement endpoints (P02 T10) ───────────────────────────────
  {
    method: 'GET',
    path: '/announcements/dashboard',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'announcement:read',
    validation: 'none',
    responseSchema: 'AnnouncementDashboardDto',
    rateTier: 'read',
    auditEvent: 'announcement.dashboard',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/announcements/unread-count',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'announcement:read',
    validation: 'none',
    responseSchema: 'UnreadCountDto',
    rateTier: 'read',
    auditEvent: 'announcement.unreadCount',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/announcements/mark-all-read',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'announcement:update',
    validation: 'none',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'announcement.markAllRead',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/announcements',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'announcement:read',
    validation: 'none',
    responseSchema: 'AnnouncementDto[]',
    rateTier: 'read',
    auditEvent: 'announcement.list',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/announcements/:id',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'announcement:read',
    validation: 'uuidParams',
    responseSchema: 'AnnouncementDto',
    rateTier: 'read',
    auditEvent: 'announcement.read',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/announcements',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:create',
    validation: 'createAnnouncementSchema',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcement.create',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/announcements/:id/read',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'announcement:update',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'announcement.markRead',
    auditFindingIds: [],
  },
  {
    method: 'PATCH',
    path: '/announcements/:id',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:update',
    validation: 'updateAnnouncementSchema',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcement.update',
    auditFindingIds: [],
  },
  {
    method: 'PATCH',
    path: '/announcements/:id/publish',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:publish',
    validation: 'uuidParams',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcement.publish',
    auditFindingIds: [],
  },
  {
    method: 'PATCH',
    path: '/announcements/:id/pin',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:pin',
    validation: 'uuidParams',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcement.togglePin',
    auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/announcements/:id',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:admin',
    resourcePolicy: 'announcement:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'announcement.delete',
    auditFindingIds: [],
  },
  {
    method: 'PATCH',
    path: '/announcements/:id/restore',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:admin',
    resourcePolicy: 'announcement:restore',
    validation: 'uuidParams',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcement.restore',
    auditFindingIds: [],
  },

  // ── Approval endpoints (P02 T10) ─────────────────────────────────
  {
    method: 'POST',
    path: '/approvals/requests/:id/route-to-ceo',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:approve',
    validation: 'uuidParams',
    responseSchema: 'ApprovalResultDto',
    rateTier: 'write',
    auditEvent: 'approval.routeToCeo',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/ceo-decision',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:approve',
    validation: 'uuidParams',
    responseSchema: 'ApprovalResultDto',
    rateTier: 'write',
    auditEvent: 'approval.ceoDecision',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/route-to-manager',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:approve',
    validation: 'uuidParams',
    responseSchema: 'ApprovalResultDto',
    rateTier: 'write',
    auditEvent: 'approval.routeToManager',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/manager-decision',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:approve',
    validation: 'uuidParams',
    responseSchema: 'ApprovalResultDto',
    rateTier: 'write',
    auditEvent: 'approval.managerDecision',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/entity-decision',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:approve',
    validation: 'uuidParams',
    responseSchema: 'ApprovalResultDto',
    rateTier: 'write',
    auditEvent: 'approval.entityDecision',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/upload-resume',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'attachment:upload',
    validation: 'multipartUpload',
    responseSchema: 'UploadResult',
    rateTier: 'write',
    auditEvent: 'approval.uploadResume',
    auditFindingIds: [7, 13],
  },
  {
    method: 'GET',
    path: '/approvals/requests/:id/candidates',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'CandidateDto[]',
    rateTier: 'read',
    auditEvent: 'approval.candidates',
    auditFindingIds: [13, 14],
  },
  {
    method: 'DELETE',
    path: '/approvals/requests/:id/candidates/:candidateId',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'approval.deleteCandidate',
    auditFindingIds: [13, 14],
  },

  // ── Approval delegation (P02 T10) ──────────────────────────────────
  {
    method: 'POST',
    path: '/approval-delegations/:approvalId/delegate',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'approval:delegate',
    validation: 'delegateSchema',
    responseSchema: 'DelegationDto',
    rateTier: 'write',
    auditEvent: 'approval.delegate',
    auditFindingIds: [13, 14],
  },
  {
    method: 'GET',
    path: '/approval-delegations/:approvalId/delegations',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'approval:read',
    validation: 'uuidParams',
    responseSchema: 'DelegationDto[]',
    rateTier: 'read',
    auditEvent: 'approval.delegationHistory',
    auditFindingIds: [13, 14],
  },
  {
    method: 'GET',
    path: '/approval-delegations/:approvalId/reminders',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'approval:read',
    validation: 'uuidParams',
    responseSchema: 'ReminderDto[]',
    rateTier: 'read',
    auditEvent: 'approval.reminderHistory',
    auditFindingIds: [13, 14],
  },

  // ── Approval policy (P02 T10) ──────────────────────────────────────
  {
    method: 'GET',
    path: '/approval-policies/request-type/:requestTypeId',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'approval-policy:list',
    validation: 'uuidParams',
    responseSchema: 'ApprovalPolicyDto[]',
    rateTier: 'read',
    auditEvent: 'approvalPolicy.listByType',
    auditFindingIds: [13, 14],
  },
  {
    method: 'GET',
    path: '/approval-policies/resolve/:requestTypeId',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'approval-policy:resolve',
    validation: 'uuidParams',
    responseSchema: 'ApprovalPolicyDto',
    rateTier: 'read',
    auditEvent: 'approvalPolicy.resolve',
    auditFindingIds: [13, 14],
  },
  {
    method: 'GET',
    path: '/approval-policies/:id',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'approval-policy:read',
    validation: 'uuidParams',
    responseSchema: 'ApprovalPolicyDto',
    rateTier: 'read',
    auditEvent: 'approvalPolicy.read',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/approval-policies',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'approval-policy:create',
    validation: 'createPolicySchema',
    responseSchema: 'ApprovalPolicyDto',
    rateTier: 'write',
    auditEvent: 'approvalPolicy.create',
    auditFindingIds: [13, 14],
  },
  {
    method: 'PUT',
    path: '/approval-policies/:id',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'approval-policy:update',
    validation: 'updatePolicySchema',
    responseSchema: 'ApprovalPolicyDto',
    rateTier: 'write',
    auditEvent: 'approvalPolicy.update',
    auditFindingIds: [13, 14],
  },
  {
    method: 'DELETE',
    path: '/approval-policies/:id',
    owner: 'Approvals',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'approval-policy:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'approvalPolicy.delete',
    auditFindingIds: [13, 14],
  },

  // ── Asset management (P02 T10) ─────────────────────────────────────
  {
    method: 'GET',
    path: '/assets',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:read',
    resourcePolicy: 'asset:list',
    validation: 'none',
    responseSchema: 'AssetDto[]',
    rateTier: 'read',
    auditEvent: 'asset.list',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/assets/assignments',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:read',
    resourcePolicy: 'asset:list-assignments',
    validation: 'none',
    responseSchema: 'AssetAssignmentDto[]',
    rateTier: 'read',
    auditEvent: 'asset.listAssignments',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/assets/by-user/:userId',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:read',
    resourcePolicy: 'asset:read',
    validation: 'uuidParams',
    responseSchema: 'AssetDto[]',
    rateTier: 'read',
    auditEvent: 'asset.listByUser',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/assets/export',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:read',
    resourcePolicy: 'asset:export',
    validation: 'none',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'asset.export',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/assets/:id',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:read',
    resourcePolicy: 'asset:read',
    validation: 'uuidParams',
    responseSchema: 'AssetDto',
    rateTier: 'read',
    auditEvent: 'asset.read',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/assets',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:write',
    resourcePolicy: 'asset:create',
    validation: 'createAssetSchema',
    responseSchema: 'AssetDto',
    rateTier: 'write',
    auditEvent: 'asset.create',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/assets/import',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:import',
    resourcePolicy: 'asset:import',
    validation: 'multipartUpload',
    responseSchema: 'ImportResult',
    rateTier: 'write',
    auditEvent: 'asset.import',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/assets/import/commit',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:import',
    resourcePolicy: 'asset:import',
    validation: 'none',
    responseSchema: 'ImportResult',
    rateTier: 'write',
    auditEvent: 'asset.importCommit',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/assets/:id/assign',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:write',
    resourcePolicy: 'asset:assign',
    validation: 'assignAssetSchema',
    responseSchema: 'AssetDto',
    rateTier: 'write',
    auditEvent: 'asset.assign',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/assets/:id/return',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:write',
    resourcePolicy: 'asset:return',
    validation: 'uuidParams',
    responseSchema: 'AssetDto',
    rateTier: 'write',
    auditEvent: 'asset.return',
    auditFindingIds: [],
  },
  {
    method: 'PATCH',
    path: '/assets/:id',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:write',
    resourcePolicy: 'asset:update',
    validation: 'updateAssetSchema',
    responseSchema: 'AssetDto',
    rateTier: 'write',
    auditEvent: 'asset.update',
    auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/assets/:id',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:delete',
    resourcePolicy: 'asset:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'asset.delete',
    auditFindingIds: [],
  },

  // ── Audit log (P02 T10) ───────────────────────────────────────────
  {
    method: 'GET',
    path: '/audit-logs',
    owner: 'Compliance',
    authentication: 'platform-admin',
    coarsePermission: 'audit:read',
    resourcePolicy: 'audit:list',
    validation: 'none',
    responseSchema: 'AuditLogDto[]',
    rateTier: 'sensitive',
    auditEvent: 'auditLog.list',
    auditFindingIds: [3, 4],
  },

  // ── Banner config (P02 T10) ────────────────────────────────────────
  {
    method: 'GET',
    path: '/banner-config/active',
    owner: 'Platform',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'banner:read',
    validation: 'none',
    responseSchema: 'BannerConfigDto',
    rateTier: 'read',
    auditEvent: 'bannerConfig.active',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/banner-config',
    owner: 'Platform',
    authentication: 'user',
    coarsePermission: 'banner:manage',
    resourcePolicy: 'banner:list',
    validation: 'none',
    responseSchema: 'BannerConfigDto[]',
    rateTier: 'read',
    auditEvent: 'bannerConfig.list',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/banner-config',
    owner: 'Platform',
    authentication: 'user',
    coarsePermission: 'banner:manage',
    resourcePolicy: 'banner:create',
    validation: 'createBannerSchema',
    responseSchema: 'BannerConfigDto',
    rateTier: 'write',
    auditEvent: 'bannerConfig.create',
    auditFindingIds: [],
  },
  {
    method: 'PUT',
    path: '/banner-config/:id',
    owner: 'Platform',
    authentication: 'user',
    coarsePermission: 'banner:manage',
    resourcePolicy: 'banner:update',
    validation: 'updateBannerSchema',
    responseSchema: 'BannerConfigDto',
    rateTier: 'write',
    auditEvent: 'bannerConfig.update',
    auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/banner-config/:id',
    owner: 'Platform',
    authentication: 'user',
    coarsePermission: 'banner:manage',
    resourcePolicy: 'banner:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'bannerConfig.delete',
    auditFindingIds: [],
  },

  // ── Catalog entitlement (P02 T10) ──────────────────────────────────
  {
    method: 'GET',
    path: '/catalog-entitlements',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:access',
    resourcePolicy: 'catalog:list',
    validation: 'none',
    responseSchema: 'CatalogEntitlementDto[]',
    rateTier: 'read',
    auditEvent: 'catalogEntitlement.list',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/catalog-entitlements/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:access',
    resourcePolicy: 'catalog:read',
    validation: 'uuidParams',
    responseSchema: 'CatalogEntitlementDto',
    rateTier: 'read',
    auditEvent: 'catalogEntitlement.read',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/catalog-entitlements',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:create',
    validation: 'createEntitlementSchema',
    responseSchema: 'CatalogEntitlementDto',
    rateTier: 'write',
    auditEvent: 'catalogEntitlement.create',
    auditFindingIds: [],
  },
  {
    method: 'PUT',
    path: '/catalog-entitlements/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:update',
    validation: 'updateEntitlementSchema',
    responseSchema: 'CatalogEntitlementDto',
    rateTier: 'write',
    auditEvent: 'catalogEntitlement.update',
    auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/catalog-entitlements/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'catalogEntitlement.delete',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/catalog-entitlements/check',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'catalog:check',
    validation: 'checkEntitlementSchema',
    responseSchema: 'EntitlementCheckResult',
    rateTier: 'read',
    auditEvent: 'catalogEntitlement.check',
    auditFindingIds: [],
  },

  // ── Knowledge base (P02 T10) ───────────────────────────────────────
  {
    method: 'GET',
    path: '/kb/articles',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'kb:list',
    validation: 'none',
    responseSchema: 'ArticleDto[]',
    rateTier: 'read',
    auditEvent: 'kb.list',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/kb/articles/:slug',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'kb:read',
    validation: 'none',
    responseSchema: 'ArticleDto',
    rateTier: 'read',
    auditEvent: 'kb.read',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/kb/articles/:id/helpful',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'kb:helpful',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'kb.markHelpful',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/kb/articles',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: 'kb:write',
    resourcePolicy: 'kb:create',
    validation: 'createArticleSchema',
    responseSchema: 'ArticleDto',
    rateTier: 'write',
    auditEvent: 'kb.create',
    auditFindingIds: [],
  },
  {
    method: 'PUT',
    path: '/kb/articles/:id',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: 'kb:write',
    resourcePolicy: 'kb:update',
    validation: 'updateArticleSchema',
    responseSchema: 'ArticleDto',
    rateTier: 'write',
    auditEvent: 'kb.update',
    auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/kb/articles/:id',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: 'kb:write',
    resourcePolicy: 'kb:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'kb.delete',
    auditFindingIds: [],
  },
  {
    method: 'PUT',
    path: '/kb/articles/:id/publish',
    owner: 'Knowledge',
    authentication: 'user',
    coarsePermission: 'kb:write',
    resourcePolicy: 'kb:publish',
    validation: 'uuidParams',
    responseSchema: 'ArticleDto',
    rateTier: 'write',
    auditEvent: 'kb.publish',
    auditFindingIds: [],
  },

  // ── Search (P02 T10) ───────────────────────────────────────────────
  {
    method: 'GET',
    path: '/search',
    owner: 'Search',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'search:global',
    validation: 'none',
    responseSchema: 'SearchResultDto',
    rateTier: 'read',
    auditEvent: 'search.global',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/search/requests',
    owner: 'Search',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'search:requests',
    validation: 'none',
    responseSchema: 'RequestDto[]',
    rateTier: 'read',
    auditEvent: 'search.requests',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/search/articles',
    owner: 'Search',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'search:articles',
    validation: 'none',
    responseSchema: 'ArticleDto[]',
    rateTier: 'read',
    auditEvent: 'search.articles',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/search/users',
    owner: 'Search',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'search:users',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'search.users',
    auditFindingIds: [],
  },

  // ── Service desk (P02 T10) ────────────────────────────────────────
  {
    method: 'GET',
    path: '/service-desks',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'serviceDesk:list',
    validation: 'none',
    responseSchema: 'ServiceDeskDto[]',
    rateTier: 'read',
    auditEvent: 'serviceDesk.list',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/service-desks/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'serviceDesk:read',
    validation: 'uuidParams',
    responseSchema: 'ServiceDeskDto',
    rateTier: 'read',
    auditEvent: 'serviceDesk.read',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/service-desks/:id/categories',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'serviceDesk:read',
    validation: 'uuidParams',
    responseSchema: 'CategoryDto[]',
    rateTier: 'read',
    auditEvent: 'serviceDesk.categories',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/service-desks/:id/request-types',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'serviceDesk:read',
    validation: 'uuidParams',
    responseSchema: 'RequestTypeDto[]',
    rateTier: 'read',
    auditEvent: 'serviceDesk.requestTypes',
    auditFindingIds: [],
  },
  {
    method: 'POST',
    path: '/service-desks',
    owner: 'Requests',
    authentication: 'platform-admin',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'serviceDesk:create',
    validation: 'createServiceDeskSchema',
    responseSchema: 'ServiceDeskDto',
    rateTier: 'write',
    auditEvent: 'serviceDesk.create',
    auditFindingIds: [],
  },
  {
    method: 'PUT',
    path: '/service-desks/:id',
    owner: 'Requests',
    authentication: 'platform-admin',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'serviceDesk:update',
    validation: 'updateServiceDeskSchema',
    responseSchema: 'ServiceDeskDto',
    rateTier: 'write',
    auditEvent: 'serviceDesk.update',
    auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/service-desks/:id',
    owner: 'Requests',
    authentication: 'platform-admin',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'serviceDesk:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'serviceDesk.delete',
    auditFindingIds: [],
  },

  // ── Reports (P02 T10) ─────────────────────────────────────────────
  {
    method: 'GET',
    path: '/reports/summary',
    owner: 'Analytics',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:summary',
    validation: 'none',
    responseSchema: 'ReportSummaryDto',
    rateTier: 'read',
    auditEvent: 'report.summary',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/reports/by-status',
    owner: 'Analytics',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:byStatus',
    validation: 'none',
    responseSchema: 'ReportByStatusDto',
    rateTier: 'read',
    auditEvent: 'report.byStatus',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/reports/by-service-desk',
    owner: 'Analytics',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:byServiceDesk',
    validation: 'none',
    responseSchema: 'ReportByServiceDeskDto',
    rateTier: 'read',
    auditEvent: 'report.byServiceDesk',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/reports/by-priority',
    owner: 'Analytics',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:byPriority',
    validation: 'none',
    responseSchema: 'ReportByPriorityDto',
    rateTier: 'read',
    auditEvent: 'report.byPriority',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/reports/agent-workload',
    owner: 'Analytics',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:agentWorkload',
    validation: 'none',
    responseSchema: 'AgentWorkloadDto',
    rateTier: 'read',
    auditEvent: 'report.agentWorkload',
    auditFindingIds: [],
  },
  {
    method: 'GET',
    path: '/reports/sla-status',
    owner: 'Analytics',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:slaStatus',
    validation: 'none',
    responseSchema: 'SlaStatusDto',
    rateTier: 'read',
    auditEvent: 'report.slaStatus',
    auditFindingIds: [],
  },

  // ── Tenant management (P02 T10) ────────────────────────────────────
  {
    method: 'GET',
    path: '/tenants',
    owner: 'Platform',
    authentication: 'platform-admin',
    coarsePermission: 'tenant:read',
    resourcePolicy: 'tenant:list',
    validation: 'none',
    responseSchema: 'TenantDto[]',
    rateTier: 'read',
    auditEvent: 'tenant.list',
    auditFindingIds: [1, 2],
  },
  {
    method: 'GET',
    path: '/tenants/:id',
    owner: 'Platform',
    authentication: 'platform-admin',
    coarsePermission: 'tenant:read',
    resourcePolicy: 'tenant:read',
    validation: 'uuidParams',
    responseSchema: 'TenantDto',
    rateTier: 'read',
    auditEvent: 'tenant.read',
    auditFindingIds: [1, 2],
  },
  {
    method: 'GET',
    path: '/tenants/:id/stats',
    owner: 'Platform',
    authentication: 'platform-admin',
    coarsePermission: 'tenant:read',
    resourcePolicy: 'tenant:stats',
    validation: 'uuidParams',
    responseSchema: 'TenantStatsDto',
    rateTier: 'read',
    auditEvent: 'tenant.stats',
    auditFindingIds: [1, 2],
  },
  {
    method: 'POST',
    path: '/tenants',
    owner: 'Platform',
    authentication: 'platform-admin',
    coarsePermission: 'tenant:create',
    resourcePolicy: 'tenant:create',
    validation: 'createTenantSchema',
    responseSchema: 'TenantDto',
    rateTier: 'write',
    auditEvent: 'tenant.create',
    auditFindingIds: [1, 2],
  },
  {
    method: 'PUT',
    path: '/tenants/:id',
    owner: 'Platform',
    authentication: 'platform-admin',
    coarsePermission: 'tenant:update',
    resourcePolicy: 'tenant:update',
    validation: 'updateTenantSchema',
    responseSchema: 'TenantDto',
    rateTier: 'write',
    auditEvent: 'tenant.update',
    auditFindingIds: [1, 2],
  },
  {
    method: 'DELETE',
    path: '/tenants/:id',
    owner: 'Platform',
    authentication: 'platform-admin',
    coarsePermission: 'tenant:delete',
    resourcePolicy: 'tenant:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'tenant.deactivate',
    auditFindingIds: [1, 2],
  },
];