import { OperationControl } from './operation-control.types';

/** Task 10 controls that were absent from the earlier bounded route batches. */
export const remainingOperationControls: OperationControl[] = [
  {
    method: 'GET', path: '/', owner: 'Workflow', authentication: 'user',
    coarsePermission: null, resourcePolicy: 'workflow:read', validation: 'none',
    responseSchema: 'WorkflowTypeDto[]', rateTier: 'read', auditEvent: 'workflow.list', auditFindingIds: [],
  },
  {
    method: 'GET', path: '/:workflowTypeId/versions', owner: 'Workflow', authentication: 'user',
    coarsePermission: null, resourcePolicy: 'workflow:read', validation: 'pathParams',
    responseSchema: 'WorkflowVersionDto[]', rateTier: 'read', auditEvent: 'workflow.versions.list', auditFindingIds: [],
  },
  {
    method: 'POST', path: '/:workflowTypeId/versions', owner: 'Workflow', authentication: 'user',
    coarsePermission: 'workflow:manage', resourcePolicy: 'workflow:create', validation: 'pathParams',
    responseSchema: 'WorkflowVersionDto', rateTier: 'write', auditEvent: 'workflow.version.create', auditFindingIds: [],
  },
  {
    method: 'GET', path: '/versions/:versionId', owner: 'Workflow', authentication: 'user',
    coarsePermission: null, resourcePolicy: 'workflow:read', validation: 'pathParams',
    responseSchema: 'WorkflowVersionDto', rateTier: 'read', auditEvent: 'workflow.version.get', auditFindingIds: [],
  },
  {
    method: 'PATCH', path: '/versions/:versionId/nodes', owner: 'Workflow', authentication: 'user',
    coarsePermission: 'workflow:manage', resourcePolicy: 'workflow:update', validation: 'pathParams',
    responseSchema: 'WorkflowGraphDto', rateTier: 'write', auditEvent: 'workflow.nodes.update', auditFindingIds: [],
  },
  {
    method: 'PATCH', path: '/versions/:versionId/edges', owner: 'Workflow', authentication: 'user',
    coarsePermission: 'workflow:manage', resourcePolicy: 'workflow:update', validation: 'pathParams',
    responseSchema: 'WorkflowGraphDto', rateTier: 'write', auditEvent: 'workflow.edges.update', auditFindingIds: [],
  },
  {
    method: 'POST', path: '/versions/:versionId/validate', owner: 'Workflow', authentication: 'user',
    coarsePermission: null, resourcePolicy: 'workflow:validate', validation: 'pathParams',
    responseSchema: 'WorkflowValidationDto', rateTier: 'read', auditEvent: 'workflow.version.validate', auditFindingIds: [],
  },
  {
    method: 'POST', path: '/versions/:versionId/publish', owner: 'Workflow', authentication: 'user',
    coarsePermission: 'workflow:manage', resourcePolicy: 'workflow:publish', validation: 'pathParams',
    responseSchema: 'WorkflowVersionDto', rateTier: 'write', auditEvent: 'workflow.version.publish', auditFindingIds: [],
  },
  {
    method: 'POST', path: '/versions/:versionId/rollback', owner: 'Workflow', authentication: 'user',
    coarsePermission: 'workflow:manage', resourcePolicy: 'workflow:rollback', validation: 'pathParams',
    responseSchema: 'WorkflowVersionDto', rateTier: 'write', auditEvent: 'workflow.version.rollback', auditFindingIds: [],
  },
  {
    method: 'DELETE', path: '/versions/:versionId', owner: 'Workflow', authentication: 'user',
    coarsePermission: 'workflow:manage', resourcePolicy: 'workflow:delete', validation: 'pathParams',
    responseSchema: 'NoContentDto', rateTier: 'sensitive', auditEvent: 'workflow.version.delete', auditFindingIds: [],
  },
  {
    method: 'DELETE',
    path: '/admin/offboarding-templates/:id',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'offboarding-template:delete',
    validation: 'pathParams',
    responseSchema: 'NoContentDto',
    rateTier: 'sensitive',
    auditEvent: 'admin.offboarding_templates.delete',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'DELETE',
    path: '/approvals/requests/:id/resumes/:resumeId',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:delete',
    validation: 'pathParams',
    responseSchema: 'NoContentDto',
    rateTier: 'sensitive',
    auditEvent: 'approvals.resumes.delete',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'DELETE',
    path: '/service-desks/:id/categories/:categoryId',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:delete',
    validation: 'pathParams',
    responseSchema: 'NoContentDto',
    rateTier: 'sensitive',
    auditEvent: 'servicedesks.categories.delete',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'DELETE',
    path: '/service-desks/request-types/:typeId',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:delete',
    validation: 'pathParams',
    responseSchema: 'NoContentDto',
    rateTier: 'sensitive',
    auditEvent: 'servicedesks.request_types.delete',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'DELETE',
    path: '/users/permissions/:permissionId',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'permission:delete',
    validation: 'pathParams',
    responseSchema: 'NoContentDto',
    rateTier: 'sensitive',
    auditEvent: 'users.permissions.delete',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'DELETE',
    path: '/users/roles/:roleId',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'role:delete',
    validation: 'pathParams',
    responseSchema: 'NoContentDto',
    rateTier: 'sensitive',
    auditEvent: 'users.roles.delete',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'GET',
    path: '/admin/offboarding-templates',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: 'admin:access',
    resourcePolicy: 'offboarding-template:read',
    validation: 'none',
    responseSchema: 'OffboardingTemplateDto',
    rateTier: 'read',
    auditEvent: 'admin.offboarding_templates.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/announcements/admin/all',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:read',
    validation: 'none',
    responseSchema: 'AnnouncementDto',
    rateTier: 'read',
    auditEvent: 'announcements.all.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/announcements/admin/trash',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:admin',
    resourcePolicy: 'announcement:read',
    validation: 'none',
    responseSchema: 'AnnouncementDto',
    rateTier: 'read',
    auditEvent: 'announcements.trash.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/approvals/policy-explainer',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'approval-policy:read',
    validation: 'none',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'read',
    auditEvent: 'approvals.policy_explainer.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/approvals/requests/:id/resumes',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:read',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'read',
    auditEvent: 'approvals.resumes.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/insights/credit/overview',
    owner: 'Reporting',
    authentication: 'user',
    coarsePermission: 'credit:read',
    resourcePolicy: 'report:read-scoped',
    validation: 'none',
    responseSchema: 'InsightDto',
    rateTier: 'read',
    auditEvent: 'insights.overview.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/insights/itsm/agent-workload',
    owner: 'Reporting',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:read-scoped',
    validation: 'none',
    responseSchema: 'InsightDto',
    rateTier: 'read',
    auditEvent: 'insights.agent_workload.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/insights/itsm/by-priority',
    owner: 'Reporting',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:read-scoped',
    validation: 'none',
    responseSchema: 'InsightDto',
    rateTier: 'read',
    auditEvent: 'insights.by_priority.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/insights/itsm/by-service-desk',
    owner: 'Reporting',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:read-scoped',
    validation: 'none',
    responseSchema: 'InsightDto',
    rateTier: 'read',
    auditEvent: 'insights.by_service_desk.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/insights/itsm/sla-compliance',
    owner: 'Reporting',
    authentication: 'user',
    coarsePermission: 'report:read',
    resourcePolicy: 'report:read-scoped',
    validation: 'none',
    responseSchema: 'InsightDto',
    rateTier: 'read',
    auditEvent: 'insights.sla_compliance.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/offboarding/requests/:id/offboarding/tasks',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:read',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'read',
    auditEvent: 'offboarding.tasks.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/onboarding/requests/:id/onboarding/tasks',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:read',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'read',
    auditEvent: 'onboarding.tasks.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/service-desks/agents',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'catalog:read',
    validation: 'queryParams',
    responseSchema: 'CatalogDto',
    rateTier: 'read',
    auditEvent: 'servicedesks.agents.getByTeam',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/service-desks/:id/agents',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'catalog:read',
    validation: 'pathParams',
    responseSchema: 'CatalogDto',
    rateTier: 'read',
    auditEvent: 'servicedesks.agents.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/service-desks/:id/categories/all',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'catalog:read',
    validation: 'pathParams',
    responseSchema: 'CatalogDto',
    rateTier: 'read',
    auditEvent: 'servicedesks.all.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/service-desks/:id/request-types/all',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'catalog:read',
    validation: 'pathParams',
    responseSchema: 'CatalogDto',
    rateTier: 'read',
    auditEvent: 'servicedesks.all.get',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'GET',
    path: '/users/executives',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:read',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'read',
    auditEvent: 'users.executives.get',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'GET',
    path: '/users/me/delegation/incoming',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'delegation:read-own',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'read',
    auditEvent: 'users.incoming.get',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'GET',
    path: '/users/me/delegation/search',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'delegation:read-own',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'read',
    auditEvent: 'users.search.get',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'GET',
    path: '/users/permissions/all',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:access',
    resourcePolicy: 'permission:read',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'read',
    auditEvent: 'users.all.get',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'GET',
    path: '/users/roles/all',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:access',
    resourcePolicy: 'role:read',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'read',
    auditEvent: 'users.all.get',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'PATCH',
    path: '/onboarding/requests/:id/onboarding/hire-info',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'onboarding.hire_info.patch',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/admin/offboarding-templates',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'offboarding-template:update',
    validation: 'none',
    responseSchema: 'OffboardingTemplateDto',
    rateTier: 'write',
    auditEvent: 'admin.offboarding_templates.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/announcements/parse-doc',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:update',
    validation: 'multipartUpload',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcements.parse_doc.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/announcements/upload-image',
    owner: 'Communications',
    authentication: 'user',
    coarsePermission: 'announcement:write',
    resourcePolicy: 'announcement:update',
    validation: 'multipartUpload',
    responseSchema: 'AnnouncementDto',
    rateTier: 'write',
    auditEvent: 'announcements.upload_image.post',
    auditFindingIds: [7, 35, 83, 84],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/group-dceo-decision-hr',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'approvals.group_dceo_decision_hr.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/mark-job-posted',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'approvals.mark_job_posted.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/route-to-group-dceo-hr',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'approvals.route_to_group_dceo_hr.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/approvals/requests/:id/upload-candidate-docs',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'multipartUpload',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'approvals.upload_candidate_docs.post',
    auditFindingIds: [7, 35, 83, 84],
  },
  {
    method: 'POST',
    path: '/assets/import/parse',
    owner: 'ITAM',
    authentication: 'user',
    coarsePermission: 'asset:import',
    resourcePolicy: 'asset:import',
    validation: 'multipartUpload',
    responseSchema: 'AssetImportPreviewDto',
    rateTier: 'write',
    auditEvent: 'assets.parse.post',
    auditFindingIds: [7, 35, 83, 84],
  },
  {
    method: 'POST',
    path: '/auth/admin-unlock',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:unlock',
    validation: 'none',
    responseSchema: 'OperationResultDto',
    rateTier: 'write',
    auditEvent: 'auth.admin_unlock.post',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'POST',
    path: '/chargeback-workflow/requests/:id/from-entity-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'chargebackworkflow.from_entity_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/chargeback-workflow/requests/:id/mark-confirmed',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'chargebackworkflow.mark_confirmed.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/chargeback-workflow/requests/:id/to-entity-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'chargebackworkflow.to_entity_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/esm-workflow/requests/:id/ceo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'esmworkflow.ceo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/esm-workflow/requests/:id/cfo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'esmworkflow.cfo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/esm-workflow/requests/:id/finance-acknowledge',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'esmworkflow.finance_acknowledge.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/esm-workflow/requests/:id/group-dceo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'esmworkflow.group_dceo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/esm-workflow/requests/:id/reassign-ceo-approver',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'esmworkflow.reassign_ceo_approver.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/cfo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.cfo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/finance-head-approve-expense',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.finance_head_approve_expense.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/finance-head-reject-expense',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.finance_head_reject_expense.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/group-dceo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.group_dceo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/manager-approve-expense',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.manager_approve_expense.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/manager-reject-expense',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.manager_reject_expense.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/mark-expense-payment-complete',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.mark_expense_payment_complete.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/route-to-cfo',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'multipartUpload',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.route_to_cfo.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/set-finalized-amount-and-route-cfo',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.set_finalized_amount_and_route_cfo.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/finance-workflow/requests/:id/update-and-close-budget',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'financeworkflow.update_and_close_budget.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/ceo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.ceo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/cfo-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.cfo_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/cto-decision',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.cto_decision.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/mark-fulfilled',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.mark_fulfilled.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/mark-hardware-ordered',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.mark_hardware_ordered.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/mark-hardware-received',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.mark_hardware_received.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/mark-software-provisioned',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.mark_software_provisioned.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/payment-done',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.payment_done.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/it-workflow/requests/:id/route-to-cfo',
    owner: 'Workflow',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'multipartUpload',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'itworkflow.route_to_cfo.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/onboarding/requests/:id/onboarding/assign-buddy',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'onboarding.assign_buddy.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/onboarding/requests/:id/onboarding/complete-milestone',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:update',
    validation: 'pathParams',
    responseSchema: 'RequestWorkflowDto',
    rateTier: 'write',
    auditEvent: 'onboarding.complete_milestone.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/service-desks/:id/categories',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:update',
    validation: 'catalogMutationSchema',
    responseSchema: 'CatalogDto',
    rateTier: 'write',
    auditEvent: 'servicedesks.categories.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/service-desks/request-types',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:update',
    validation: 'catalogMutationSchema',
    responseSchema: 'CatalogDto',
    rateTier: 'write',
    auditEvent: 'servicedesks.request_types.post',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'POST',
    path: '/users/:id/reset-password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:update',
    validation: 'pathParams',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.reset_password.post',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'POST',
    path: '/users/import',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:update',
    validation: 'multipartUpload',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.import.post',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'POST',
    path: '/users/permissions',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'permission:update',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.permissions.post',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'POST',
    path: '/users/roles',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'role:update',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.roles.post',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'PUT',
    path: '/admin/offboarding-templates/:id',
    owner: 'HR Services',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'offboarding-template:update',
    validation: 'pathParams',
    responseSchema: 'OffboardingTemplateDto',
    rateTier: 'write',
    auditEvent: 'admin.offboarding_templates.put',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'PUT',
    path: '/service-desks/:id/categories/reorder',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:update',
    validation: 'categoryReorderSchema',
    responseSchema: 'CatalogDto',
    rateTier: 'write',
    auditEvent: 'servicedesks.categories.reorder',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'PUT',
    path: '/service-desks/:id/categories/:categoryId',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:update',
    validation: 'catalogMutationSchema',
    responseSchema: 'CatalogDto',
    rateTier: 'write',
    auditEvent: 'servicedesks.categories.put',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'PUT',
    path: '/service-desks/request-types/:typeId',
    owner: 'Catalog',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'catalog:update',
    validation: 'catalogMutationSchema',
    responseSchema: 'CatalogDto',
    rateTier: 'write',
    auditEvent: 'servicedesks.request_types.put',
    auditFindingIds: [8, 35, 75, 78],
  },
  {
    method: 'PUT',
    path: '/users/me/delegation',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'delegation:update-own',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.delegation.put',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'PUT',
    path: '/users/me/out-of-office',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:update-own',
    validation: 'none',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.out_of_office.put',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'PUT',
    path: '/users/roles/:roleId',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'role:update',
    validation: 'pathParams',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.roles.put',
    auditFindingIds: [6, 29, 35],
  },
  {
    method: 'PUT',
    path: '/users/roles/:roleId/permissions',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'admin:settings',
    resourcePolicy: 'role:update',
    validation: 'pathParams',
    responseSchema: 'UserAdminDto',
    rateTier: 'write',
    auditEvent: 'users.permissions.put',
    auditFindingIds: [6, 29, 35],
  },
];
