/**
 * Operation Control Registry — the single source of truth for security
 * metadata on every API operation.
 *
 * Every route in backend/src/routes/ and backend/src/credit/routes/ MUST have
 * a corresponding entry here. The coverage test (operation-control.coverage.test.ts)
 * will fail the build if any operation is missing or duplicate.
 *
 * Batch 1 (P01): Critical user, file, notification, PDF, export endpoints.
 * Batch 2 (P02 T9): Request domain endpoints — secured with authorizeResource.
 *
 * @see backend/src/security/operation-control.types.ts
 */

import { OperationControl } from './operation-control.types';

export const operationControls: OperationControl[] = [
  // ── User endpoints (finding #6, #35) ──────────────────────────────
  {
    method: 'GET',
    path: '/users',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.list',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:read',
    validation: 'uuidParams',
    responseSchema: 'UserSummaryDto',
    rateTier: 'read',
    auditEvent: 'user.read',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:update',
    resourcePolicy: 'user:update',
    validation: 'updateUserSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.update',
    auditFindingIds: [6, 35],
  },
  {
    method: 'DELETE',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:delete',
    resourcePolicy: 'user:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.delete',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/users',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:create',
    validation: 'createUserSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.create',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/me',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:read-own',
    validation: 'none',
    responseSchema: 'UserProfileDto',
    rateTier: 'read',
    auditEvent: 'user.me',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/me',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:update-own',
    validation: 'updateProfileSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.updateMe',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/me/password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'user:change-password',
    validation: 'changePasswordSchema',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.changePassword',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/agents',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list-agents',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.listAgents',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/staff',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list-staff',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.listStaff',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/search',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:search',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.search',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/users/:id/roles',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:manage',
    resourcePolicy: 'user:assign-roles',
    validation: 'assignRolesSchema',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.assignRoles',
    auditFindingIds: [6, 35],
  },

  // ── Auth endpoints (finding #6, #35) ──────────────────────────────
  {
    method: 'POST',
    path: '/auth/login',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:login',
    validation: 'loginSchema',
    responseSchema: 'AuthResponse',
    rateTier: 'auth',
    auditEvent: 'auth.login',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/logout',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:logout',
    validation: 'none',
    responseSchema: 'none',
    rateTier: 'auth',
    auditEvent: 'auth.logout',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/refresh',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:refresh',
    validation: 'none',
    responseSchema: 'AuthResponse',
    rateTier: 'auth',
    auditEvent: 'auth.refresh',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/forgot-password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:forgot-password',
    validation: 'forgotPasswordSchema',
    responseSchema: 'none',
    rateTier: 'auth',
    auditEvent: 'auth.forgotPassword',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/reset-password',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:reset-password',
    validation: 'resetPasswordSchema',
    responseSchema: 'none',
    rateTier: 'auth',
    auditEvent: 'auth.resetPassword',
    auditFindingIds: [6, 35],
  },

  // ── File download (finding #7, #83, #84) ──────────────────────────
  {
    method: 'GET',
    path: '/files/download/*',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'file:download',
    resourcePolicy: 'attachment:download',
    validation: 'none',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'file.download',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'POST',
    path: '/files/upload',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'file:upload',
    resourcePolicy: 'attachment:upload',
    validation: 'multipartUpload',
    responseSchema: 'UploadResult',
    rateTier: 'write',
    auditEvent: 'file.upload',
    auditFindingIds: [7, 83, 84],
  },

  // ── Request endpoints (P02 T9 — secured with authorizeResource) ───
  {
    method: 'GET',
    path: '/requests',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:list',
    validation: 'none',
    responseSchema: 'RequestListDto',
    rateTier: 'read',
    auditEvent: 'request.list',
    auditFindingIds: [8, 10, 11, 12, 16, 55],
  },
  {
    method: 'POST',
    path: '/requests',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:create',
    resourcePolicy: 'request:create',
    validation: 'createRequestSchema',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.create',
    auditFindingIds: [8, 10, 12, 19],
  },
  {
    method: 'GET',
    path: '/requests/pending-approvals',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:list-pending',
    validation: 'none',
    responseSchema: 'RequestListDto',
    rateTier: 'read',
    auditEvent: 'request.pendingApprovals',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'POST',
    path: '/requests/bulk-action',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:approve',
    resourcePolicy: 'request:bulk-action',
    validation: 'none',
    responseSchema: 'BulkActionResult',
    rateTier: 'write',
    auditEvent: 'request.bulkAction',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'GET',
    path: '/requests/recent-services',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'request:list-own',
    validation: 'none',
    responseSchema: 'ServiceTypeDto[]',
    rateTier: 'read',
    auditEvent: 'request.recentServices',
    auditFindingIds: [8, 10],
  },
  {
    method: 'POST',
    path: '/requests/export/xlsx',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'request:export',
    validation: 'exportFilterSchema',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.export.xlsx',
    auditFindingIds: [35],
  },
  {
    method: 'GET',
    path: '/requests/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'RequestDto',
    rateTier: 'read',
    auditEvent: 'request.read',
    auditFindingIds: [8, 10, 11, 16, 55],
  },
  {
    method: 'PUT',
    path: '/requests/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'updateRequestSchema',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.update',
    auditFindingIds: [8, 10, 12, 16],
  },
  {
    method: 'DELETE',
    path: '/requests/:id',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:delete',
    resourcePolicy: 'request:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'request.delete',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'GET',
    path: '/requests/:id/export/pdf',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'request:export',
    validation: 'uuidParams',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.export.pdf',
    auditFindingIds: [35],
  },
  {
    method: 'GET',
    path: '/requests/:id/activities',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'ActivityDto[]',
    rateTier: 'read',
    auditEvent: 'request.activity.list',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/requests/:id/activities',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'addActivitySchema',
    responseSchema: 'ActivityDto',
    rateTier: 'write',
    auditEvent: 'request.activity.add',
    auditFindingIds: [13, 14],
  },
  {
    method: 'POST',
    path: '/requests/:id/attachments',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'attachment:upload',
    validation: 'multipartUpload',
    responseSchema: 'AttachmentDto',
    rateTier: 'write',
    auditEvent: 'request.attachment.upload',
    auditFindingIds: [7, 13, 14],
  },
  {
    method: 'GET',
    path: '/requests/:id/attachments/:attachmentId',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'attachment:download',
    validation: 'uuidParams',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.attachment.download',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'DELETE',
    path: '/requests/:id/attachments/:attachmentId',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'attachment:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'request.attachment.delete',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'PUT',
    path: '/requests/:id/assign',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'uuidParams',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.assign',
    auditFindingIds: [8, 10, 12],
  },
  {
    method: 'PUT',
    path: '/requests/:id/status',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'request:update',
    validation: 'uuidParams',
    responseSchema: 'RequestDto',
    rateTier: 'write',
    auditEvent: 'request.updateStatus',
    auditFindingIds: [8, 10, 12],
  },

  // ── Request participants (finding #13–#16) ─────────────────────────
  {
    method: 'GET',
    path: '/requests/:id/participants',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'ParticipantDto[]',
    rateTier: 'read',
    auditEvent: 'request.participant.list',
    auditFindingIds: [13, 14, 15, 16],
  },
  {
    method: 'POST',
    path: '/requests/:id/participants',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'addParticipantSchema',
    responseSchema: 'ParticipantDto',
    rateTier: 'write',
    auditEvent: 'request.participant.add',
    auditFindingIds: [15, 16],
  },
  {
    method: 'DELETE',
    path: '/requests/:id/participants/:userId',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'request.participant.remove',
    auditFindingIds: [15, 16],
  },

  // ── Notification mutations (finding #17, #18) ──────────────────────
  {
    method: 'GET',
    path: '/notifications',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:list',
    validation: 'none',
    responseSchema: 'NotificationDto[]',
    rateTier: 'read',
    auditEvent: 'notification.list',
    auditFindingIds: [17, 18],
  },
  {
    method: 'GET',
    path: '/notifications/unread-count',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:list',
    validation: 'none',
    responseSchema: 'UnreadCountDto',
    rateTier: 'read',
    auditEvent: 'notification.unreadCount',
    auditFindingIds: [17, 18],
  },
  {
    method: 'PUT',
    path: '/notifications/:id/read',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:update',
    validation: 'uuidParams',
    responseSchema: 'NotificationDto',
    rateTier: 'write',
    auditEvent: 'notification.markRead',
    auditFindingIds: [17, 18],
  },
  {
    method: 'PUT',
    path: '/notifications/read-all',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:update',
    validation: 'none',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'notification.markAllRead',
    auditFindingIds: [17, 18],
  },
  {
    method: 'DELETE',
    path: '/notifications/:id',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'notification.delete',
    auditFindingIds: [17, 18],
  },

  // ── PDF jobs (finding #83, #84) ────────────────────────────────────
  {
    method: 'GET',
    path: '/pdf-jobs/:jobId',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'pdfJob:read',
    validation: 'uuidParams',
    responseSchema: 'PdfJobDto',
    rateTier: 'read',
    auditEvent: 'pdfJob.read',
    auditFindingIds: [83, 84],
  },

  // ── Departments (P02 T7) ──────────────────────────────────────────
  {
    method: 'GET',
    path: '/departments',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'department:read',
    resourcePolicy: 'department:list',
    validation: 'none',
    responseSchema: 'DepartmentDto[]',
    rateTier: 'read',
    auditEvent: 'department.list',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'GET',
    path: '/departments/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'department:read',
    resourcePolicy: 'department:read',
    validation: 'uuidParams',
    responseSchema: 'DepartmentDto',
    rateTier: 'read',
    auditEvent: 'department.read',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'POST',
    path: '/departments',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:create',
    validation: 'createDepartmentSchema',
    responseSchema: 'DepartmentDto',
    rateTier: 'write',
    auditEvent: 'department.create',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'PUT',
    path: '/departments/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:update',
    validation: 'updateDepartmentSchema',
    responseSchema: 'DepartmentDto',
    rateTier: 'write',
    auditEvent: 'department.update',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'DELETE',
    path: '/departments/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'department.delete',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'POST',
    path: '/departments/:id/members',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:manage-members',
    validation: 'addMemberSchema',
    responseSchema: 'MembershipDto',
    rateTier: 'write',
    auditEvent: 'department.addMember',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'DELETE',
    path: '/departments/members/:membershipId',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'department:manage',
    resourcePolicy: 'department:manage-members',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'department.removeMember',
    auditFindingIds: [1, 2, 29, 30],
  },
  {
    method: 'GET',
    path: '/departments/grants/:userId',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'department:read',
    resourcePolicy: 'department:read-grants',
    validation: 'uuidParams',
    responseSchema: 'PrincipalGrantDto[]',
    rateTier: 'read',
    auditEvent: 'department.grants',
    auditFindingIds: [1, 2, 29, 30],
  },
];