/**
 * Operation Control Registry — the single source of truth for security
 * metadata on every API operation.
 *
 * Every route in backend/src/routes/ and backend/src/credit/routes/ MUST have
 * a corresponding entry here. The coverage test
 * (operation-control.coverage.test.ts) will fail the build if any operation
 * is missing or duplicate.
 *
 * Phase P01 seeds critical operations for findings #6, #7, #13–#18, #35,
 * #83–#84.  Subsequent tasks will fill in every remaining operation until
 * 876/876 have complete metadata.
 *
 * @see backend/src/security/operation-control.types.ts
 */

import { OperationControl } from './operation-control.types';

export const operationControls: OperationControl[] = [
  // ── User endpoints (finding #6, #35) ──────────────────────────────
  {
    method: 'GET',
    path: '/users',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:list',
    validation: 'none',
    responseSchema: 'UserSummaryDto[]',
    rateTier: 'read',
    auditEvent: 'user.list',
    auditFindingIds: [6, 35],
  },
  {
    method: 'GET',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:read',
    resourcePolicy: 'user:read',
    validation: 'uuidParams',
    responseSchema: 'UserSummaryDto',
    rateTier: 'read',
    auditEvent: 'user.read',
    auditFindingIds: [6, 35],
  },
  {
    method: 'PUT',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: 'user:update',
    resourcePolicy: 'user:update',
    validation: 'updateUserSchema',
    responseSchema: 'UserProfileDto',
    rateTier: 'write',
    auditEvent: 'user.update',
    auditFindingIds: [6, 35],
  },
  {
    method: 'DELETE',
    path: '/users/:id',
    owner: 'IAM',
    authentication: 'platform-admin',
    coarsePermission: 'user:delete',
    resourcePolicy: 'user:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'sensitive',
    auditEvent: 'user.delete',
    auditFindingIds: [6, 35],
  },
  {
    method: 'POST',
    path: '/auth/login',
    owner: 'IAM',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'auth:login',
    validation: 'loginSchema',
    responseSchema: 'AuthResponse',
    rateTier: 'auth',
    auditEvent: 'auth.login',
    auditFindingIds: [6, 35],
  },

  // ── File download (finding #7, #83, #84) ──────────────────────────
  {
    method: 'GET',
    path: '/files/download/*',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'file:download',
    resourcePolicy: 'attachment:download',
    validation: 'none',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'file.download',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'POST',
    path: '/files/upload',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'file:upload',
    resourcePolicy: 'attachment:upload',
    validation: 'multipartUpload',
    responseSchema: 'UploadResult',
    rateTier: 'write',
    auditEvent: 'file.upload',
    auditFindingIds: [7, 83, 84],
  },

  // ── Request activities (finding #13, #14) ─────────────────────────
  {
    method: 'GET',
    path: '/requests/:id/activities',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'request:read',
    validation: 'uuidParams',
    responseSchema: 'ActivityDto[]',
    rateTier: 'read',
    auditEvent: 'request.activity.list',
    auditFindingIds: [13, 14],
  },

  // ── Request participants (finding #15, #16) ────────────────────────
  {
    method: 'POST',
    path: '/requests/:id/participants',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:assign',
    resourcePolicy: 'request:assign',
    validation: 'addParticipantSchema',
    responseSchema: 'ParticipantDto',
    rateTier: 'write',
    auditEvent: 'request.participant.add',
    auditFindingIds: [15, 16],
  },

  // ── Notification mutations (finding #17, #18) ──────────────────────
  {
    method: 'GET',
    path: '/notifications',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:list',
    validation: 'none',
    responseSchema: 'NotificationDto[]',
    rateTier: 'read',
    auditEvent: 'notification.list',
    auditFindingIds: [17, 18],
  },
  {
    method: 'PUT',
    path: '/notifications/:id/read',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:update',
    validation: 'uuidParams',
    responseSchema: 'NotificationDto',
    rateTier: 'write',
    auditEvent: 'notification.markRead',
    auditFindingIds: [17, 18],
  },
  {
    method: 'PUT',
    path: '/notifications/read-all',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:update',
    validation: 'none',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'notification.markAllRead',
    auditFindingIds: [17, 18],
  },
  {
    method: 'DELETE',
    path: '/notifications/:id',
    owner: 'Notifications',
    authentication: 'user',
    coarsePermission: null,
    resourcePolicy: 'notification:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'notification.delete',
    auditFindingIds: [17, 18],
  },

  // ── PDF jobs (finding #83, #84) ────────────────────────────────────
  {
    method: 'GET',
    path: '/pdf-jobs/:jobId',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'pdfJob:read',
    validation: 'uuidParams',
    responseSchema: 'PdfJobDto',
    rateTier: 'read',
    auditEvent: 'pdfJob.read',
    auditFindingIds: [83, 84],
  },

  // ── Request export (finding #35) ──────────────────────────────────
  {
    method: 'POST',
    path: '/requests/export/xlsx',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'request:export',
    validation: 'exportFilterSchema',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.export.xlsx',
    auditFindingIds: [35],
  },
  {
    method: 'GET',
    path: '/requests/:id/export/pdf',
    owner: 'Requests',
    authentication: 'user',
    coarsePermission: 'request:export',
    resourcePolicy: 'request:export',
    validation: 'uuidParams',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.export.pdf',
    auditFindingIds: [35],
  },

  // ── Attachment download/delete (finding #7, #83, #84) ──────────────
  {
    method: 'GET',
    path: '/requests/:id/attachments/:attachmentId',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:read',
    resourcePolicy: 'attachment:download',
    validation: 'uuidParams',
    responseSchema: 'Stream',
    rateTier: 'sensitive',
    auditEvent: 'request.attachment.download',
    auditFindingIds: [7, 83, 84],
  },
  {
    method: 'DELETE',
    path: '/requests/:id/attachments/:attachmentId',
    owner: 'File Security',
    authentication: 'user',
    coarsePermission: 'request:update',
    resourcePolicy: 'attachment:delete',
    validation: 'uuidParams',
    responseSchema: 'none',
    rateTier: 'write',
    auditEvent: 'request.attachment.delete',
    auditFindingIds: [7, 83, 84],
  },
];